# Generated by Django 5.2.4 on 2026-05-18 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0005_alter_workorder_produced_qty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Chờ nhận hàng"), ("received", "Đã nhận hàng"), ("cancelled", "Đã hủy")],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Tổng tiền"),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_invoices",
                        to="master_data.supplier",
                        verbose_name="Nhà cung cấp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Invoice",
                "verbose_name_plural": "Purchase Invoices",
                "db_table": "purchase_invoice",
            },
        ),
        migrations.CreateModel(
            name="PurchaseInvoiceLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Số lượng")),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Đơn giá")),
                (
                    "import_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Thuế nhập khẩu"),
                ),
                ("vat_tax", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Thuế VAT")),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Thành tiền"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchasing.purchaseinvoice",
                        verbose_name="Hóa đơn",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="master_data.item", verbose_name="Sản phẩm"
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Invoice Line",
                "verbose_name_plural": "Purchase Invoice Lines",
                "db_table": "purchase_invoice_line",
            },
        ),
    ]
