# Generated by Django 5.2.4 on 2026-05-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoice",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Đã thanh toán"),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ nhận hàng"),
                    ("received", "Đã nhận hàng"),
                    ("partial", "Thanh toán một phần"),
                    ("paid", "Đã thanh toán"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
