# Generated by Django 5.2.4 on 2026-05-20 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "__first__"),
        ("purchasing", "0003_alter_purchaseinvoice_status_purchaseorder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_invoices",
                to="procurement.supplier",
                verbose_name="Nhà cung cấp",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="procurement.supplier",
                verbose_name="Nhà cung cấp",
            ),
        ),
    ]
