# Generated by Django 5.2.4 on 2026-06-04 09:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_stockentry_status"),
        ("procurement", "0002_create_supplier_table"),
        ("purchasing", "0005_purchaseinvoice_stock_entry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("shipment_num", models.CharField(max_length=100, unique=True, verbose_name="Mã lô hàng")),
                ("name", models.CharField(max_length=255, verbose_name="Tên lô hàng/Hồ sơ lô hàng")),
                (
                    "total_logistic_fees",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=15, verbose_name="Tổng chi phí logistic"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Nháp"), ("completed", "Hoàn tất")],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "db_table": "shipment",
            },
        ),
        migrations.AddField(
            model_name="purchaseinvoice",
            name="block_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Lý do chặn thanh toán"),
        ),
        migrations.AddField(
            model_name="purchaseinvoice",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Hạn thanh toán"),
        ),
        migrations.AddField(
            model_name="purchaseinvoice",
            name="qty_fulfillment_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Tỷ lệ hoàn thành số lượng tổng (%)"
            ),
        ),
        migrations.AddField(
            model_name="purchaseinvoiceline",
            name="qty_fulfillment_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Tỷ lệ hoàn thành số lượng dòng (%)"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Chưa thanh toán"),
                    ("partial", "Thanh toán một phần"),
                    ("paid", "Đã thanh toán"),
                    ("blocked_for_payment", "Bị chặn thanh toán"),
                    ("cancelled", "Đã hủy"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseinvoice",
            index=models.Index(fields=["due_date", "status", "vendor"], name="purchase_in_due_dat_735b6c_idx"),
        ),
    ]
