# Generated by Django 5.2.4 on 2026-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0006_shipment_purchaseinvoice_block_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp (Đang đi đường)"),
                    ("arrived", "Đã cập bến (Chờ QC)"),
                    ("inspected", "Đã kiểm định (Chờ nhập kho)"),
                    ("completed", "Hoàn tất"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
