# Generated by Django 5.2.4 on 2026-06-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0007_alter_shipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày giao hàng dự kiến"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_fulfillment_rate",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Tiến độ thanh toán (%)"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="receipt_fulfillment_rate",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Tiến độ nhận hàng tổng (%)"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="receipt_fulfillment_rate",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Tiến độ nhận hàng dòng (%)"
            ),
        ),
    ]
