# Generated by Django 5.2.4 on 2026-06-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0008_purchaseorder_expected_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp"),
                    ("pending", "Chờ xử lý"),
                    ("paid_unshipped", "Đã thanh toán, chưa nhận hàng"),
                    ("shipped_unpaid", "Đã nhận hàng, chưa thanh toán"),
                    ("completed", "Hoàn tất"),
                    ("cancel_pending", "Chờ duyệt hủy"),
                    ("cancelled", "Đã hủy"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
