# Generated by Django 5.2.4 on 2026-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0009_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseinvoice",
            name="block_reason",
        ),
        migrations.RemoveField(
            model_name="purchaseinvoice",
            name="qty_fulfillment_rate",
        ),
        migrations.RemoveField(
            model_name="purchaseinvoiceline",
            name="qty_fulfillment_rate",
        ),
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Chưa thanh toán"),
                    ("partial", "Thanh toán một phần"),
                    ("paid", "Đã thanh toán"),
                    ("cancelled", "Đã hủy"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
