# Generated by Django 5.2.4 on 2026-06-13 15:33

import django.db.models.deletion
from django.db import migrations, models


def map_shipment_statuses(apps, schema_editor):
    Shipment = apps.get_model("purchasing", "Shipment")
    Shipment.objects.filter(status="arrived").update(status="inspecting")
    Shipment.objects.filter(status="inspected").update(status="inspecting")


def reverse_map_shipment_statuses(apps, schema_editor):
    Shipment = apps.get_model("purchasing", "Shipment")
    Shipment.objects.filter(status="inspecting").update(status="arrived")


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0010_remove_purchaseinvoice_block_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="purchasing.purchaseorder",
                verbose_name="Đơn mua hàng",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[("draft", "Nháp (Chờ hàng về)"), ("inspecting", "Đang tiếp nhận"), ("completed", "Hoàn tất")],
                default="draft",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.RunPython(map_shipment_statuses, reverse_map_shipment_statuses),
    ]
