# Generated by Django 5.2.4 on 2026-06-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_stockentry_posted_at_alter_stockentry_posting_date"),
        ("procurement", "0002_create_supplier_table"),
        ("purchasing", "0011_shipment_purchase_order_alter_shipment_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="purchaseinvoice",
            name="purchase_in_due_dat_735b6c_idx",
        ),
        migrations.RemoveField(
            model_name="purchaseinvoice",
            name="due_date",
        ),
        migrations.AddIndex(
            model_name="purchaseinvoice",
            index=models.Index(fields=["status", "vendor"], name="purchase_in_status_55d1ff_idx"),
        ),
    ]
