# Generated by Django 5.2.4 on 2026-06-29 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_stockentry_posted_at_alter_stockentry_posting_date"),
        ("procurement", "0002_create_supplier_table"),
        ("purchasing", "0012_remove_purchaseinvoice_purchase_in_due_dat_735b6c_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="purchaseinvoice",
            name="purchase_in_status_55d1ff_idx",
        ),
        migrations.AddField(
            model_name="purchaseinvoice",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Hạn thanh toán"),
        ),
        migrations.AddIndex(
            model_name="purchaseinvoice",
            index=models.Index(fields=["due_date", "status", "vendor"], name="purchase_in_due_dat_735b6c_idx"),
        ),
    ]
