# Generated by Django 5.2.4 on 2026-06-29 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0013_remove_purchaseinvoice_purchase_in_status_55d1ff_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Hạn thanh toán"),
        ),
    ]
