# Generated by Django 5.2.4 on 2026-06-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0014_purchaseorder_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp (Chờ hàng về)"),
                    ("inspecting", "Đang tiếp nhận"),
                    ("pending_approval", "Chờ duyệt"),
                    ("completed", "Hoàn tất"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
