# Generated by Django 5.2.4 on 2026-05-19 03:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0005_alter_workorder_produced_qty_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Chưa thanh toán"),
                    ("partial", "Thanh toán một phần"),
                    ("paid", "Đã thanh toán"),
                    ("cancelled", "Đã hủy"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("pending", "Chờ giao hàng"),
                            ("completed", "Hoàn tất"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Tổng tiền"),
                ),
                (
                    "advance_paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Đã ứng trước"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="master_data.customer",
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order",
                "verbose_name_plural": "Sales Orders",
                "db_table": "sales_order",
            },
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="sales.salesorder",
                verbose_name="Đơn hàng gốc",
            ),
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Số lượng")),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Đơn giá")),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Thành tiền"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="master_data.item", verbose_name="Sản phẩm"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesorder",
                        verbose_name="Đơn hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order Line",
                "verbose_name_plural": "Sales Order Lines",
                "db_table": "sales_order_line",
            },
        ),
    ]
