# Generated by Django 5.2.4 on 2026-05-20 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "__first__"),
        ("sales", "0002_alter_salesinvoice_status_salesorder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_invoices",
                to="crm.customer",
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_orders",
                to="crm.customer",
                verbose_name="Khách hàng",
            ),
        ),
    ]
