# Generated by Django 5.2.4 on 2026-05-20 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockentry_purchase_order_stockentry_sales_order"),
        ("sales", "0003_alter_salesinvoice_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="stock_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_invoices",
                to="inventory.stockentry",
                verbose_name="Phiếu xuất kho",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp"),
                    ("pending", "Chờ xử lý"),
                    ("paid_unshipped", "Đã nhận tiền, chưa giao hàng"),
                    ("shipped_unpaid", "Đã giao hàng, chưa thanh toán"),
                    ("completed", "Hoàn tất"),
                    ("cancelled", "Đã hủy"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
