# Generated by Django 5.2.4 on 2026-06-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_salesinvoice_stock_entry_alter_salesorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Chưa thanh toán"),
                    ("partial", "Thanh toán một phần"),
                    ("paid", "Đã thanh toán"),
                    ("cancelled", "Đã hủy"),
                ],
                db_index=True,
                default="unpaid",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp"),
                    ("pending", "Chờ xử lý"),
                    ("pending_credit_approval", "Chờ duyệt tín dụng"),
                    ("paid_unshipped", "Đã nhận tiền, chưa giao hàng"),
                    ("shipped_unpaid", "Đã giao hàng, chưa thanh toán"),
                    ("completed", "Hoàn tất"),
                    ("cancelled", "Đã hủy"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Trạng thái",
            ),
        ),
    ]
