# Generated by Django 5.2.4 on 2026-06-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_salesinvoice_status_alter_salesorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp"),
                    ("pending", "Chờ xử lý"),
                    ("pending_credit_approval", "Chờ duyệt tín dụng"),
                    ("paid_unshipped", "Đã nhận tiền, chưa giao hàng"),
                    ("shipped_unpaid", "Đã giao hàng, chưa thanh toán"),
                    ("completed", "Hoàn tất"),
                    ("cancel_pending", "Chờ duyệt hủy"),
                    ("cancelled", "Đã hủy"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Trạng thái",
            ),
        ),
    ]
