# Generated by Django 5.2.4 on 2026-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_salesorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="payment_fulfillment_rate",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Tiến độ thanh toán (%)"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="receipt_fulfillment_rate",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Tiến độ giao hàng tổng (%)"
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="receipt_fulfillment_rate",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Tiến độ giao hàng (%)"
            ),
        ),
    ]
