# Generated by Django 5.2.4 on 2026-06-29 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_salesorder_payment_fulfillment_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Hạn thanh toán"),
        ),
    ]
