# Generated by Django 5.2.4 on 2026-06-29 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_salesinvoice_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Hạn thanh toán"),
        ),
    ]
