# Generated by Django 5.2.4 on 2026-05-20 17:16

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.conf import settings


def seed_roles_permissions_and_users(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Permission = apps.get_model("accounts", "Permission")
    RolePermission = apps.get_model("accounts", "RolePermission")
    User = apps.get_model("accounts", "User")

    # 1. Setup Roles
    admin_role, _ = Role.objects.get_or_create(
        name="Admin", defaults={"description": "Quản trị viên hệ thống với toàn quyền truy cập."}
    )
    employee_role, _ = Role.objects.get_or_create(name="Employee", defaults={"description": "Standard employee role"})

    # 2. Setup Permissions and assign to Admin
    system_permissions = [
        {"code": "inventory.stock_in", "name": "Nhập Kho"},
        {"code": "inventory.stock_in_approve", "name": "Duyệt Nhập Kho"},
        {"code": "inventory.stock_issue", "name": "Xuất Kho"},
        {"code": "inventory.stock_issue_approve", "name": "Duyệt Xuất Kho"},
        {"code": "inventory.stock_transfer", "name": "Chuyển Kho"},
        {"code": "inventory.stock_transfer_approve", "name": "Duyệt Chuyển Kho"},
        {"code": "inventory.view", "name": "Xem Tồn Kho"},
        {"code": "manufacturing.bom_create", "name": "Tạo BOM"},
        {"code": "manufacturing.bom_delete", "name": "Xóa BOM"},
        {"code": "manufacturing.bom_update", "name": "Cập nhật BOM"},
        {"code": "manufacturing.bom_view", "name": "Xem BOM"},
        {"code": "manufacturing.work_order_view", "name": "Xem Lệnh Sản Xuất"},
        {"code": "manufacturing.work_order_complete", "name": "Hoàn thành Lệnh Sản Xuất"},
        {"code": "manufacturing.work_order_create", "name": "Tạo Lệnh Sản Xuất"},
        {"code": "manufacturing.work_order_approve", "name": "Phê duyệt Lệnh Sản Xuất"},
        {"code": "manufacturing.work_order_declare", "name": "Nhập liệu Lệnh Sản Xuất"},
        {"code": "master_data.add_item", "name": "Thêm Sản Phẩm"},
        {"code": "master_data.change_item", "name": "Sửa Sản Phẩm"},
        {"code": "master_data.delete_item", "name": "Xóa Sản Phẩm"},
        {"code": "master_data.view_item", "name": "Xem Sản Phẩm"},
        # Phân hệ Purchasing (Mua hàng)
        {"code": "purchasing.create_order", "name": "Tạo Đơn Mua"},
        {"code": "purchasing.update_order", "name": "Sửa Đơn Mua"},
        {"code": "purchasing.delete_order", "name": "Xóa Đơn Mua"},
        {"code": "purchasing.view_order", "name": "Xem Đơn Mua"},
        {"code": "purchasing.create_invoice", "name": "Lập Hóa Đơn Mua"},
        {"code": "purchasing.receive_goods", "name": "Xác Nhận Nhận Hàng"},
        {"code": "purchasing.view_invoice", "name": "Xem Hóa Đơn Mua"},
        # Phân hệ Sales (Bán hàng)
        {"code": "sales.create_order", "name": "Tạo Đơn Bán"},
        {"code": "sales.update_order", "name": "Sửa Đơn Bán"},
        {"code": "sales.delete_order", "name": "Xóa Đơn Bán"},
        {"code": "sales.view_order", "name": "Xem Đơn Bán"},
        {"code": "sales.deliver_goods", "name": "Xác Nhận Giao Hàng"},
        {"code": "sales.create_invoice", "name": "Lập Hóa Đơn Bán"},
        {"code": "sales.view_invoice", "name": "Xem Hóa Đơn Bán"},
        # Phân hệ Finance (Tài chính)
        {"code": "finance.create_cash_flow", "name": "Tạo Phiếu Dòng Tiền"},
        {"code": "finance.view_cash_flow", "name": "Xem Phiếu Dòng Tiền"},
        # Phân hệ CRM (Khách hàng)
        {"code": "crm.customer_create", "name": "Tạo Khách Hàng"},
        {"code": "crm.customer_update", "name": "Sửa Khách Hàng"},
        {"code": "crm.customer_delete", "name": "Xóa Khách Hàng"},
        {"code": "crm.customer_view", "name": "Xem Khách Hàng"},
        # Phân hệ Procurement (Nhà cung cấp)
        {"code": "procurement.supplier_create", "name": "Tạo Nhà Cung Cấp"},
        {"code": "procurement.supplier_update", "name": "Sửa Nhà Cung Cấp"},
        {"code": "procurement.supplier_delete", "name": "Xóa Nhà Cung Cấp"},
        {"code": "procurement.supplier_view", "name": "Xem Nhà Cung Cấp"},
    ]

    for perm_data in system_permissions:
        perm, _ = Permission.objects.get_or_create(
            code=perm_data["code"],
            defaults={"name": perm_data["name"]},
        )
        RolePermission.objects.get_or_create(role=admin_role, permission=perm)

    # 3. Setup Test Users (only in DEBUG mode)
    if getattr(settings, "DEBUG", False):
        Employee = apps.get_model("master_data", "Employee")
        Employee.objects.get_or_create(
            employee_id="NV0001",
            defaults={
                "full_name": "Nguyễn Văn An",
                "email": "nv0001@erp.com",
                "phone": "0987654301",
                "gender": "male",
                "employment_status": "active",
            },
        )
        Employee.objects.get_or_create(
            employee_id="NV0002",
            defaults={
                "full_name": "Trần Thị Bình",
                "email": "nv0002@erp.com",
                "phone": "0987654302",
                "gender": "female",
                "employment_status": "active",
            },
        )

        User.objects.get_or_create(
            username="admin",
            defaults={
                "email": "admin@example.com",
                "password_hash": make_password("admin123"),
                "role": admin_role,
                "employee_id": "NV0001",
            },
        )
        User.objects.get_or_create(
            username="employee",
            defaults={
                "email": "employee@example.com",
                "password_hash": make_password("employee123"),
                "role": employee_role,
                "employee_id": "NV0002",
            },
        )


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("master_data", "0008_employee_address_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_roles_permissions_and_users, reverse_seed),
    ]
