# Generated by Django 5.2.4 on 2026-06-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_work_order_cancel_and_payroll_approve_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlog",
            name="record_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="accounts.role"
            ),
        ),
    ]
