# Generated by Django 5.2.4 on 2026-06-16 19:12

from django.db import migrations


def migrate_roles_to_direct_permissions(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    UserPermission = apps.get_model("accounts", "UserPermission")
    RolePermission = apps.get_model("accounts", "RolePermission")

    for user in User.objects.all():
        if user.role_id:
            role_perms = RolePermission.objects.filter(role_id=user.role_id)
            for rp in role_perms:
                UserPermission.objects.get_or_create(
                    user=user,
                    permission=rp.permission,
                )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_add_user_management_permissions"),
    ]

    operations = [
        migrations.RunPython(migrate_roles_to_direct_permissions, elidable=True),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
