# Generated by Django 5.2.4 on 2026-06-16

from django.db import migrations


def assign_all_permissions_to_admin(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Permission = apps.get_model("accounts", "Permission")
    UserPermission = apps.get_model("accounts", "UserPermission")

    admin_user = User.objects.filter(username="admin").first()
    if admin_user:
        all_perms = Permission.objects.all()
        for perm in all_perms:
            UserPermission.objects.get_or_create(
                user=admin_user,
                permission=perm,
            )


def reverse_assign(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_remove_user_email_remove_user_role"),
    ]

    operations = [
        migrations.RunPython(assign_all_permissions_to_admin, reverse_assign),
    ]
