# Generated by Django 5.2.4 on 2026-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_assign_all_permissions_to_admin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RolePermission",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.AddField(
            model_name="systemlog",
            name="allowed_permissions",
            field=models.JSONField(blank=True, default=list, help_text="Danh sách permissions được phép xem log này"),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(fields=["-timestamp"], name="system_log_timesta_40cc07_idx"),
        ),
    ]
