# Generated by Django 5.2.4 on 2026-06-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_rename_credit_bypass_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemlog",
            name="record_code",
            field=models.CharField(blank=True, help_text="Mã/Tên bản ghi lưu tĩnh", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="user_repr",
            field=models.CharField(blank=True, help_text="Tên người thực hiện lưu tĩnh", max_length=255, null=True),
        ),
    ]
