# Generated by Django 5.2.4 on 2026-05-22 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20260521_0016"),
        ("hrm", "0001_initial"),
        ("master_data", "0008_employee_address_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("contract_scan", "Scan hợp đồng"),
                            ("id_copy", "Bản sao CCCD/CMND"),
                            ("certification", "Bằng cấp/Chứng chỉ"),
                            ("resignation_letter", "Đơn xin nghỉ việc"),
                            ("disciplinary_minutes", "Biên bản kỷ luật"),
                            ("medical_doc", "Giấy khám sức khỏe"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_url", models.CharField(max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="master_data.employee"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="accounts.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Document",
                "verbose_name_plural": "Employee Documents",
                "db_table": "employee_document",
            },
        ),
        migrations.CreateModel(
            name="EmploymentContract",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("contract_no", models.CharField(max_length=100, unique=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("probation", "Thử việc"),
                            ("definite_term", "Xác định thời hạn"),
                            ("indefinite_term", "Không xác định thời hạn"),
                            ("other", "Khác"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("active", "Đang hoạt động"),
                            ("expired", "Hết hạn"),
                            ("terminated", "Chấm dứt"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("file_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contracts", to="master_data.employee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Employment Contract",
                "verbose_name_plural": "Employment Contracts",
                "db_table": "employment_contract",
            },
        ),
    ]
