# Generated by Django 5.2.4 on 2026-05-22 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20260521_0016"),
        ("hrm", "0002_employeedocument_employmentcontract"),
        ("master_data", "0008_employee_address_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("salary_change", "Thay đổi lương"),
                            ("title_change", "Thay đổi chức danh"),
                            ("department_transfer", "Điều chuyển phòng ban"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                    ),
                ),
                ("old_salary_base", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("new_salary_base", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("old_title", models.CharField(blank=True, max_length=100, null=True)),
                ("new_title", models.CharField(blank=True, max_length=100, null=True)),
                ("old_department", models.CharField(blank=True, max_length=100, null=True)),
                ("new_department", models.CharField(blank=True, max_length=100, null=True)),
                ("effective_date", models.DateField()),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_histories",
                        to="accounts.user",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_histories",
                        to="master_data.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employment History",
                "verbose_name_plural": "Employment Histories",
                "db_table": "employment_history",
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
    ]
