# Generated by Django 5.2.4 on 2026-05-22 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20260521_0016"),
        ("hrm", "0003_employmenthistory"),
        ("master_data", "0008_employee_address_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="overtime_hours",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="attendance",
            name="work_hours",
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("working", "Đi làm"),
                    ("paid_leave", "Nghỉ phép có lương"),
                    ("unpaid_leave", "Nghỉ không lương"),
                    ("sick_leave", "Nghỉ ốm"),
                    ("holiday", "Nghỉ lễ"),
                    ("other", "Khác"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Nghỉ phép năm"),
                            ("sick", "Nghỉ ốm"),
                            ("unpaid", "Nghỉ không lương"),
                            ("maternity", "Nghỉ thai sản"),
                            ("personal", "Nghỉ việc riêng"),
                            ("other", "Khác"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days", models.DecimalField(decimal_places=1, max_digits=4)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="accounts.user",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="master_data.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "leave_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
