# Generated by Django 5.2.4 on 2026-05-22 18:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_salaryslip_allowance_amount_salaryslip_base_salary_and_more"),
        ("hrm", "0004_attendance_overtime_hours_attendance_work_hours_and_more"),
        ("master_data", "0008_employee_address_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplineRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("incident_date", models.DateField()),
                ("discipline_date", models.DateField()),
                (
                    "discipline_type",
                    models.CharField(
                        choices=[
                            ("reprimand", "Khiển trách"),
                            ("warning", "Cảnh cáo"),
                            ("salary_deduction", "Khấu trừ lương"),
                            ("termination", "Sa thải"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("penalty_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("file_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplines",
                        to="master_data.employee",
                    ),
                ),
                (
                    "salary_slip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disciplines",
                        to="finance.salaryslip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discipline Record",
                "verbose_name_plural": "Discipline Records",
                "db_table": "discipline_record",
                "ordering": ["-discipline_date"],
            },
        ),
        migrations.CreateModel(
            name="RewardRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reward_date", models.DateField()),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("performance_bonus", "Thưởng hiệu quả công việc"),
                            ("initiative", "Sáng kiến"),
                            ("holiday_bonus", "Thưởng lễ tết"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("description", models.TextField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rewards", to="master_data.employee"
                    ),
                ),
                (
                    "salary_slip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewards",
                        to="finance.salaryslip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward Record",
                "verbose_name_plural": "Reward Records",
                "db_table": "reward_record",
                "ordering": ["-reward_date"],
            },
        ),
    ]
