# Generated by Django 5.2.4 on 2026-05-23 03:01

import random
from datetime import date, timedelta
from decimal import Decimal
from django.db import migrations
from django.conf import settings
from django.utils import timezone


def seed_hrm_data(apps, schema_editor):
    # Seed HRM data đã chuyển sang setup-data/setup_dashboard_data.py
    pass


def reverse_seed(apps, schema_editor):
    Employee = apps.get_model("master_data", "Employee")
    Attendance = apps.get_model("hrm", "Attendance")
    LeaveRequest = apps.get_model("hrm", "LeaveRequest")
    EmploymentContract = apps.get_model("hrm", "EmploymentContract")
    RewardRecord = apps.get_model("hrm", "RewardRecord")
    DisciplineRecord = apps.get_model("hrm", "DisciplineRecord")
    EmploymentHistory = apps.get_model("hrm", "EmploymentHistory")
    EmployeeDocument = apps.get_model("hrm", "EmployeeDocument")
    SalarySlip = apps.get_model("finance", "SalarySlip")
    CashFlowTransaction = apps.get_model("finance", "CashFlowTransaction")

    mock_emp_ids = [f"NV{i:03d}" for i in range(1, 11)]
    employees_to_delete = Employee.objects.filter(employee_id__in=mock_emp_ids)

    Attendance.objects.filter(employee__in=employees_to_delete).delete()
    LeaveRequest.objects.filter(employee__in=employees_to_delete).delete()
    EmploymentContract.objects.filter(employee__in=employees_to_delete).delete()
    RewardRecord.objects.filter(employee__in=employees_to_delete).delete()
    DisciplineRecord.objects.filter(employee__in=employees_to_delete).delete()
    EmploymentHistory.objects.filter(employee__in=employees_to_delete).delete()
    EmployeeDocument.objects.filter(employee__in=employees_to_delete).delete()
    SalarySlip.objects.filter(employee__in=employees_to_delete).delete()

    CashFlowTransaction.objects.filter(name__startswith="PAY-SALARY-NV").delete()
    employees_to_delete.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0005_disciplinerecord_rewardrecord"),
        ("accounts", "0002_auto_20260521_0016"),
    ]

    operations = [
        migrations.RunPython(seed_hrm_data, reverse_seed),
    ]
