# Generated by Django 5.2.4 on 2026-05-23 03:01

import random
from datetime import date, timedelta
from decimal import Decimal
from django.db import migrations
from django.conf import settings
from django.utils import timezone


def seed_hrm_data(apps, schema_editor):
    if not getattr(settings, "DEBUG", False):
        return

    # Lấy các models thông qua context apps của Django migration
    User = apps.get_model("accounts", "User")
    Employee = apps.get_model("master_data", "Employee")
    Attendance = apps.get_model("hrm", "Attendance")
    LeaveRequest = apps.get_model("hrm", "LeaveRequest")
    EmploymentContract = apps.get_model("hrm", "EmploymentContract")
    RewardRecord = apps.get_model("hrm", "RewardRecord")
    DisciplineRecord = apps.get_model("hrm", "DisciplineRecord")
    EmploymentHistory = apps.get_model("hrm", "EmploymentHistory")
    SalarySlip = apps.get_model("finance", "SalarySlip")
    CashFlowTransaction = apps.get_model("finance", "CashFlowTransaction")

    # 1. Tìm admin user để làm người phê duyệt/thực hiện
    admin_user = User.objects.filter(role__name__iexact="Admin").first()
    if not admin_user:
        admin_user = User.objects.filter(username="admin").first()
    if not admin_user:
        admin_user = User.objects.first()

    if not admin_user:
        # Nếu chưa có user nào, không thể seed vì thiếu khóa ngoại
        return

    # Danh sách mã nhân viên giả lập
    mock_emp_ids = [f"NV{i:03d}" for i in range(1, 11)]

    # Dọn dẹp dữ liệu cũ liên quan đến các nhân viên mock này nếu đã tồn tại
    employees_to_delete = Employee.objects.filter(employee_id__in=mock_emp_ids)

    Attendance.objects.filter(employee__in=employees_to_delete).delete()
    LeaveRequest.objects.filter(employee__in=employees_to_delete).delete()
    EmploymentContract.objects.filter(employee__in=employees_to_delete).delete()
    RewardRecord.objects.filter(employee__in=employees_to_delete).delete()
    DisciplineRecord.objects.filter(employee__in=employees_to_delete).delete()
    EmploymentHistory.objects.filter(employee__in=employees_to_delete).delete()
    SalarySlip.objects.filter(employee__in=employees_to_delete).delete()

    CashFlowTransaction.objects.filter(name__startswith="PAY-SALARY-NV").delete()

    employees_to_delete.delete()

    # 2. Tạo danh sách nhân sự mới
    employees_data = [
        {
            "employee_id": "NV001",
            "full_name": "Nguyễn Văn An",
            "department": "Hành chính Nhân sự",
            "position_title": "Trưởng phòng",
            "salary_base": Decimal("18000000.00"),
            "is_union_member": True,
            "email": "an.nv@example.com",
            "phone": "0987654321",
            "gender": "male",
            "date_of_birth": date(1988, 5, 15),
            "address": "123 Đường Láng, Đống Đa, Hà Nội",
            "join_date": date(2023, 1, 15),
            "employment_status": "active",
        },
        {
            "employee_id": "NV002",
            "full_name": "Trần Thị Bình",
            "department": "Hành chính Nhân sự",
            "position_title": "Chuyên viên tuyển dụng",
            "salary_base": Decimal("11000000.00"),
            "is_union_member": True,
            "email": "binh.tt@example.com",
            "phone": "0912345678",
            "gender": "female",
            "date_of_birth": date(1993, 10, 20),
            "address": "456 Kim Mã, Ba Đình, Hà Nội",
            "join_date": date(2024, 3, 1),
            "employment_status": "active",
        },
        {
            "employee_id": "NV003",
            "full_name": "Lê Hoàng Nam",
            "department": "Kỹ thuật",
            "position_title": "Trưởng phòng Kỹ thuật",
            "salary_base": Decimal("26000000.00"),
            "is_union_member": True,
            "email": "nam.lh@example.com",
            "phone": "0904445555",
            "gender": "male",
            "date_of_birth": date(1985, 2, 28),
            "address": "789 Nguyễn Trãi, Thanh Xuân, Hà Nội",
            "join_date": date(2022, 6, 1),
            "employment_status": "active",
        },
        {
            "employee_id": "NV004",
            "full_name": "Phạm Minh Đức",
            "department": "Kỹ thuật",
            "position_title": "Lập trình viên Senior",
            "salary_base": Decimal("18000000.00"),
            "is_union_member": False,
            "email": "duc.pm@example.com",
            "phone": "0933332211",
            "gender": "male",
            "date_of_birth": date(1992, 11, 8),
            "address": "12 Cầu Giấy, Cầu Giấy, Hà Nội",
            "join_date": date(2024, 7, 15),
            "employment_status": "active",
        },
        {
            "employee_id": "NV005",
            "full_name": "Vũ Thị Hồng",
            "department": "Kỹ thuật",
            "position_title": "Lập trình viên Junior",
            "salary_base": Decimal("12500000.00"),
            "is_union_member": False,
            "email": "hong.vt@example.com",
            "phone": "0977889900",
            "gender": "female",
            "date_of_birth": date(1998, 4, 3),
            "address": "88 Trần Duy Hưng, Cầu Giấy, Hà Nội",
            "join_date": date(2025, 2, 1),
            "employment_status": "active",
        },
        {
            "employee_id": "NV006",
            "full_name": "Hoàng Văn Hải",
            "department": "Kinh doanh",
            "position_title": "Trưởng phòng Kinh doanh",
            "salary_base": Decimal("20000000.00"),
            "is_union_member": False,
            "email": "hai.hv@example.com",
            "phone": "0966554433",
            "gender": "male",
            "date_of_birth": date(1987, 8, 12),
            "address": "250 Minh Khai, Hai Bà Trưng, Hà Nội",
            "join_date": date(2023, 5, 10),
            "employment_status": "active",
        },
        {
            "employee_id": "NV007",
            "full_name": "Ngô Thanh Vân",
            "department": "Kinh doanh",
            "position_title": "Nhân viên Kinh doanh",
            "salary_base": Decimal("9500000.00"),
            "is_union_member": False,
            "email": "van.nt@example.com",
            "phone": "0944112233",
            "gender": "female",
            "date_of_birth": date(1995, 12, 25),
            "address": "30 Lạc Long Quân, Tây Hồ, Hà Nội",
            "join_date": date(2024, 11, 1),
            "employment_status": "active",
        },
        {
            "employee_id": "NV008",
            "full_name": "Đỗ Anh Tuấn",
            "department": "Kế toán",
            "position_title": "Kế toán trưởng",
            "salary_base": Decimal("19000000.00"),
            "is_union_member": True,
            "email": "tuan.da@example.com",
            "phone": "0911223344",
            "gender": "male",
            "date_of_birth": date(1989, 7, 30),
            "address": "15 Hàng Bông, Hoàn Kiếm, Hà Nội",
            "join_date": date(2023, 10, 1),
            "employment_status": "active",
        },
        {
            "employee_id": "NV009",
            "full_name": "Nguyễn Mai Chi",
            "department": "Kế toán",
            "position_title": "Kế toán viên",
            "salary_base": Decimal("11500000.00"),
            "is_union_member": True,
            "email": "chi.nm@example.com",
            "phone": "0988776655",
            "gender": "female",
            "date_of_birth": date(1996, 9, 14),
            "address": "77 Tây Sơn, Đống Đa, Hà Nội",
            "join_date": date(2025, 1, 1),
            "employment_status": "active",
        },
        {
            "employee_id": "NV010",
            "full_name": "Bùi Quốc Anh",
            "department": "Kỹ thuật",
            "position_title": "Thực tập sinh",
            "salary_base": Decimal("5000000.00"),
            "is_union_member": False,
            "email": "quocanh.b@example.com",
            "phone": "0977112233",
            "gender": "male",
            "date_of_birth": date(2003, 3, 20),
            "address": "150 Hoàng Quốc Việt, Cầu Giấy, Hà Nội",
            "join_date": date(2026, 4, 1),
            "employment_status": "active",
        },
    ]

    created_employees = []
    for emp_data in employees_data:
        emp = Employee.objects.create(**emp_data)
        created_employees.append(emp)

        # 3. Tạo hợp đồng lao động tương ứng
        contract_type = "definite_term"
        if emp.position_title in ["Trưởng phòng", "Trưởng phòng Kỹ thuật", "Trưởng phòng Kinh doanh", "Kế toán trưởng"]:
            contract_type = "indefinite_term"
        elif emp.position_title == "Thực tập sinh":
            contract_type = "probation"

        end_date = None
        if contract_type == "definite_term":
            end_date = emp.join_date + timedelta(days=730)
        elif contract_type == "probation":
            end_date = emp.join_date + timedelta(days=60)

        EmploymentContract.objects.create(
            employee=emp,
            contract_no=f"HDLD/{emp.join_date.year}/{emp.employee_id}",
            contract_type=contract_type,
            start_date=emp.join_date,
            end_date=end_date,
            status="active",
            note=f"Hợp đồng lao động mẫu cho {emp.full_name}",
        )

    # 4. Tạo Employment History
    emp001 = created_employees[0]
    EmploymentHistory.objects.create(
        employee=emp001,
        change_type="salary_change",
        old_salary_base=Decimal("15000000.00"),
        new_salary_base=Decimal("18000000.00"),
        effective_date=date(2026, 1, 1),
        approved_by=admin_user,
        reason="Tăng lương định kỳ hàng năm dựa trên đánh giá hiệu suất.",
    )

    emp003 = created_employees[2]
    EmploymentHistory.objects.create(
        employee=emp003,
        change_type="title_change",
        old_title="Kỹ sư phần mềm Senior",
        new_title="Trưởng phòng Kỹ thuật",
        old_salary_base=Decimal("20000000.00"),
        new_salary_base=Decimal("26000000.00"),
        effective_date=date(2025, 10, 1),
        approved_by=admin_user,
        reason="Thăng chức quản lý bộ phận kỹ thuật thay thế trưởng phòng cũ.",
    )

    # 5. Tạo đơn nghỉ phép (Leave Request)
    # NV002: Nghỉ phép năm 2 ngày (Đã duyệt)
    emp002 = created_employees[1]
    lr1 = LeaveRequest.objects.create(
        employee=emp002,
        leave_type="annual",
        start_date=date(2026, 5, 12),
        end_date=date(2026, 5, 13),
        days=Decimal("2.0"),
        reason="Giải quyết việc cá nhân gia đình ở quê.",
        status="approved",
        approved_by=admin_user,
        approved_at=timezone.now(),
    )

    # NV004: Nghỉ ốm 1 ngày (Đã duyệt)
    emp004 = created_employees[3]
    lr2 = LeaveRequest.objects.create(
        employee=emp004,
        leave_type="sick",
        start_date=date(2026, 5, 15),
        end_date=date(2026, 5, 15),
        days=Decimal("1.0"),
        reason="Sốt virus, xin nghỉ đi khám bệnh.",
        status="approved",
        approved_by=admin_user,
        approved_at=timezone.now(),
    )

    # NV007: Nghỉ việc riêng 1 ngày (Chờ duyệt)
    emp007 = created_employees[6]
    LeaveRequest.objects.create(
        employee=emp007,
        leave_type="personal",
        start_date=date(2026, 5, 27),
        end_date=date(2026, 5, 27),
        days=Decimal("1.0"),
        reason="Đi làm thủ tục giấy tờ hành chính.",
        status="pending",
    )

    # NV009: Nghỉ phép năm 1 ngày (Từ chối)
    emp009 = created_employees[8]
    LeaveRequest.objects.create(
        employee=emp009,
        leave_type="annual",
        start_date=date(2026, 5, 8),
        end_date=date(2026, 5, 8),
        days=Decimal("1.0"),
        reason="Xin nghỉ đi du lịch cá nhân.",
        status="rejected",
        approved_by=admin_user,
        approved_at=timezone.now(),
    )

    # 6. Đồng bộ đơn nghỉ phép đã duyệt sang Attendance trước
    status_map = {
        "annual": "paid_leave",
        "sick": "sick_leave",
        "unpaid": "unpaid_leave",
        "maternity": "paid_leave",
        "personal": "unpaid_leave",
        "other": "other",
    }

    for lr in [lr1, lr2]:
        attendance_status = status_map.get(lr.leave_type, "other")
        curr = lr.start_date
        while curr <= lr.end_date:
            Attendance.objects.create(
                employee=lr.employee,
                date=curr,
                status=attendance_status,
                work_hours=Decimal("0.00"),
                overtime_hours=Decimal("0.00"),
                remarks=f"Tự động đồng bộ từ Đơn nghỉ phép ID {lr.id}",
            )
            curr += timedelta(days=1)

    # 7. Định cấu hình cho các kỳ lương seed
    periods_config = [
        {
            "salary_period": "2026-03",
            "start_date": date(2026, 3, 1),
            "end_date": date(2026, 3, 31),
            "standard_days": Decimal("22.00"),
            "draft_employee_ids": [],  # 100% paid
        },
        {
            "salary_period": "2026-04",
            "start_date": date(2026, 4, 1),
            "end_date": date(2026, 4, 30),
            "standard_days": Decimal("22.00"),
            "draft_employee_ids": ["NV004", "NV005"],  # 2 nhân viên nợ lương
        },
        {
            "salary_period": "2026-05",
            "start_date": date(2026, 5, 1),
            "end_date": date(2026, 5, 22),
            "standard_days": Decimal("22.00"),
            "draft_employee_ids": ["NV003", "NV004", "NV005", "NV006", "NV007", "NV008", "NV009", "NV010"],
        },
    ]

    # 8. Tạo khen thưởng & kỷ luật cho kỳ 2026-05
    # NV003: Thưởng sáng kiến
    RewardRecord.objects.create(
        employee=created_employees[2],
        reward_date=date(2026, 5, 18),
        reward_type="initiative",
        amount=Decimal("2000000.00"),
        description="Khen thưởng sáng kiến cải tiến quy trình DevOps.",
    )

    # NV007: Thưởng hiệu quả
    RewardRecord.objects.create(
        employee=created_employees[6],
        reward_date=date(2026, 5, 20),
        reward_type="performance_bonus",
        amount=Decimal("1500000.00"),
        description="Thưởng nóng vượt chỉ tiêu doanh số tuần.",
    )

    # NV004: Kỷ luật phạt tiền đi muộn
    DisciplineRecord.objects.create(
        employee=created_employees[3],
        incident_date=date(2026, 5, 10),
        discipline_date=date(2026, 5, 12),
        discipline_type="warning",
        penalty_amount=Decimal("200000.00"),
        description="Cảnh cáo đi làm muộn quá 5 lần trong tháng.",
    )

    # 9. Chạy vòng lặp seed dữ liệu chấm công, bảng lương cho các kỳ
    for config in periods_config:
        period_year = config["start_date"].year
        period_month = config["start_date"].month
        period_str = config["salary_period"]

        # 9.1. Tạo chấm công hàng ngày (trừ thứ 7, CN)
        delta = timedelta(days=1)
        current_date = config["start_date"]
        while current_date <= config["end_date"]:
            if current_date.weekday() in [5, 6]:
                current_date += delta
                continue

            for emp in created_employees:
                # Đảm bảo nhân sự đã join_date trước hoặc trong ngày chấm công
                if emp.join_date > current_date:
                    continue

                exists = Attendance.objects.filter(employee=emp, date=current_date).exists()
                if exists:
                    continue

                # OT chỉ áp dụng cho tháng 5
                overtime = Decimal("0.00")
                remarks = None
                if period_str == "2026-05" and emp.department == "Kỹ thuật" and current_date.weekday() in [1, 3]:
                    if (emp.employee_id == "NV003" and current_date.day in [12, 19]) or (
                        emp.employee_id == "NV004" and current_date.day in [5, 14]
                    ):
                        overtime = Decimal("2.00")
                        remarks = "OT hỗ trợ triển khai hệ thống ngoài giờ"

                Attendance.objects.create(
                    employee=emp,
                    date=current_date,
                    status="working",
                    work_hours=Decimal("8.00"),
                    overtime_hours=overtime,
                    remarks=remarks,
                )
            current_date += delta

        # 9.2. Tính toán lương cho từng nhân sự hoạt động trong kỳ
        for emp in created_employees:
            # Chỉ tính lương nếu nhân viên đã join_date trước hoặc trong kỳ lương này
            # (tức là join_date có tháng/năm <= period_month/year)
            emp_join_date = emp.join_date
            if emp_join_date.year > period_year or (
                emp_join_date.year == period_year and emp_join_date.month > period_month
            ):
                continue

            salary_base = emp.salary_base or Decimal("0.00")

            # Đếm ngày công thực tế từ Attendance
            attendances = Attendance.objects.filter(employee=emp, date__year=period_year, date__month=period_month)
            working_days = Decimal("0.00")
            paid_leave_days = Decimal("0.00")
            total_ot_hours = Decimal("0.00")

            for att in attendances:
                if att.status == "working":
                    working_days += Decimal("1.00")
                elif att.status in ["paid_leave", "sick_leave", "holiday"]:
                    paid_leave_days += Decimal("1.00")
                total_ot_hours += att.overtime_hours or Decimal("0.00")

            # Tính base_salary_earned
            base_salary_earned = (salary_base * ((working_days + paid_leave_days) / config["standard_days"])).quantize(
                Decimal("0.01")
            )

            # Tính overtime_amount_earned
            hourly_rate = salary_base / config["standard_days"] / Decimal("8.00")
            ot_rate = hourly_rate * Decimal("1.5")
            overtime_amount_earned = (total_ot_hours * ot_rate).quantize(Decimal("0.01"))

            # Phí công đoàn 2%
            union_fee = Decimal("0.00")
            if emp.is_union_member:
                union_fee = (salary_base * Decimal("0.02")).quantize(Decimal("0.01"))

            # Thưởng
            rewards = RewardRecord.objects.filter(
                employee=emp, reward_date__year=period_year, reward_date__month=period_month
            )
            reward_total = Decimal("0.00")
            for r in rewards:
                reward_total += r.amount or Decimal("0.00")

            # Phạt
            disciplines = DisciplineRecord.objects.filter(
                employee=emp, discipline_date__year=period_year, discipline_date__month=period_month
            )
            discipline_total = Decimal("0.00")
            for d in disciplines:
                discipline_total += d.penalty_amount or Decimal("0.00")

            gross_pay = base_salary_earned + overtime_amount_earned
            deductions = union_fee + discipline_total
            net_pay = gross_pay + reward_total - deductions

            status = "draft"
            payment_method = None
            if emp.employee_id not in config["draft_employee_ids"]:
                status = "paid"
                payment_method = "bank_transfer"

            slip = SalarySlip.objects.create(
                name=f"SALARY-{emp.employee_id}-{period_str}",
                employee=emp,
                salary_period=period_str,
                base_salary=base_salary_earned,
                overtime_amount=overtime_amount_earned,
                allowance_amount=Decimal("0.00"),
                reward_amount_total=reward_total,
                discipline_deduction_total=discipline_total,
                union_fee_2pct=union_fee,
                gross_pay=gross_pay,
                deductions=deductions,
                net_pay=net_pay,
                payment_method=payment_method,
                status=status,
                remarks="Bảng lương mẫu tự động seed.",
            )

            # Liên kết Reward/Discipline vào slip lương
            for r in rewards:
                r.salary_slip = slip
                r.save()
            for d in disciplines:
                d.salary_slip = slip
                d.save()

            # 10. Tạo bút toán CashFlowTransaction nếu phiếu lương đã thanh toán
            if status == "paid":
                CashFlowTransaction.objects.create(
                    name=f"PAY-SALARY-{emp.employee_id}-{period_str}",
                    payment_type="pay",
                    category="Chi trả lương nhân viên",
                    amount=net_pay,
                    payment_date=config["end_date"],
                    remarks=f"Thanh toán lương tháng {period_month:02d}/{period_year} cho nhân viên {emp.full_name} ({emp.employee_id}).",
                )


def reverse_seed(apps, schema_editor):
    Employee = apps.get_model("master_data", "Employee")
    Attendance = apps.get_model("hrm", "Attendance")
    LeaveRequest = apps.get_model("hrm", "LeaveRequest")
    EmploymentContract = apps.get_model("hrm", "EmploymentContract")
    RewardRecord = apps.get_model("hrm", "RewardRecord")
    DisciplineRecord = apps.get_model("hrm", "DisciplineRecord")
    EmploymentHistory = apps.get_model("hrm", "EmploymentHistory")
    EmployeeDocument = apps.get_model("hrm", "EmployeeDocument")
    SalarySlip = apps.get_model("finance", "SalarySlip")
    CashFlowTransaction = apps.get_model("finance", "CashFlowTransaction")

    mock_emp_ids = [f"NV{i:03d}" for i in range(1, 11)]
    employees_to_delete = Employee.objects.filter(employee_id__in=mock_emp_ids)

    Attendance.objects.filter(employee__in=employees_to_delete).delete()
    LeaveRequest.objects.filter(employee__in=employees_to_delete).delete()
    EmploymentContract.objects.filter(employee__in=employees_to_delete).delete()
    RewardRecord.objects.filter(employee__in=employees_to_delete).delete()
    DisciplineRecord.objects.filter(employee__in=employees_to_delete).delete()
    EmploymentHistory.objects.filter(employee__in=employees_to_delete).delete()
    EmployeeDocument.objects.filter(employee__in=employees_to_delete).delete()
    SalarySlip.objects.filter(employee__in=employees_to_delete).delete()

    CashFlowTransaction.objects.filter(name__startswith="PAY-SALARY-NV").delete()
    employees_to_delete.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0005_disciplinerecord_rewardrecord"),
        ("accounts", "0002_auto_20260521_0016"),
    ]

    operations = [
        migrations.RunPython(seed_hrm_data, reverse_seed),
    ]
