# Generated by Django 5.2.4 on 2026-05-25 04:03

from django.db import migrations, models


def convert_leave_types(apps, schema_editor):
    LeaveRequest = apps.get_model("hrm", "LeaveRequest")
    # 'annual', 'sick', 'maternity' -> 'paid'
    LeaveRequest.objects.filter(leave_type__in=["annual", "sick", "maternity"]).update(leave_type="paid")
    # 'unpaid', 'personal', 'other' -> 'unpaid'
    LeaveRequest.objects.filter(leave_type__in=["personal", "other"]).update(leave_type="unpaid")


def rollback_leave_types(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0006_auto_20260523_1001"),
    ]

    operations = [
        migrations.RunPython(convert_leave_types, rollback_leave_types),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(choices=[("paid", "Nghỉ có lương"), ("unpaid", "Nghỉ không lương")], max_length=20),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
