# Generated by Django 5.2.4 on 2026-05-25 04:07

import uuid
from django.db import migrations, models
from django.conf import settings


def seed_public_holidays(apps, schema_editor):
    if not getattr(settings, "DEBUG", False):
        return

    PublicHoliday = apps.get_model("hrm", "PublicHoliday")

    holidays_data = [
        {"name": "Tết Dương Lịch", "date": "2026-01-01", "description": "Nghỉ Tết Dương Lịch 1 ngày"},
        {"name": "Giỗ tổ Hùng Vương", "date": "2026-04-26", "description": "Giỗ tổ Hùng Vương (10/3 Âm lịch)"},
        {"name": "Ngày Giải phóng Miền Nam", "date": "2026-04-30", "description": "Giải phóng Miền Nam 30/4"},
        {"name": "Ngày Quốc tế Lao động", "date": "2026-05-01", "description": "Quốc tế Lao động 1/5"},
        {"name": "Ngày Quốc khánh", "date": "2026-09-02", "description": "Quốc khánh 2/9"},
    ]

    for item in holidays_data:
        PublicHoliday.objects.update_or_create(
            date=item["date"], defaults={"name": item["name"], "description": item["description"]}
        )


def rollback_public_holidays(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0007_alter_leaverequest_leave_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Public Holiday",
                "verbose_name_plural": "Public Holidays",
                "db_table": "public_holiday",
                "ordering": ["-date"],
            },
        ),
        migrations.RunPython(seed_public_holidays, rollback_public_holidays),
    ]
