# Generated by Django 5.2.4 on 2026-05-26 02:36

from django.db import migrations, models
from django.conf import settings


def update_public_holiday_seed(apps, schema_editor):
    if not getattr(settings, "DEBUG", False):
        return

    PublicHoliday = apps.get_model("hrm", "PublicHoliday")

    # Clean up old seed data to avoid key collisions or duplicates
    old_dates = ["2026-01-01", "2026-04-26", "2026-04-30", "2026-05-01", "2026-09-02"]
    PublicHoliday.objects.filter(start_date__in=old_dates).delete()
    PublicHoliday.objects.filter(name="Tết Nguyên Đán 2026").delete()

    holidays_data = [
        {"name": "Tết Dương Lịch", "start_date": "2026-01-01", "days": 1, "description": "Nghỉ Tết Dương Lịch 1 ngày"},
        {
            "name": "Tết Nguyên Đán 2026",
            "start_date": "2026-02-17",
            "days": 5,
            "description": "Nghỉ Tết Nguyên Đán 5 ngày",
        },
        {
            "name": "Giỗ tổ Hùng Vương",
            "start_date": "2026-04-26",
            "days": 1,
            "description": "Giỗ tổ Hùng Vương (10/3 Âm lịch)",
        },
        {
            "name": "Ngày Giải phóng Miền Nam",
            "start_date": "2026-04-30",
            "days": 1,
            "description": "Giải phóng Miền Nam 30/4",
        },
        {"name": "Ngày Quốc tế Lao động", "start_date": "2026-05-01", "days": 1, "description": "Quốc tế Lao động 1/5"},
        {"name": "Ngày Quốc khánh", "start_date": "2026-09-02", "days": 1, "description": "Quốc khánh 2/9"},
    ]

    for item in holidays_data:
        PublicHoliday.objects.update_or_create(
            start_date=item["start_date"],
            defaults={
                "name": item["name"],
                "days": item["days"],
                "description": item["description"],
            },
        )


def rollback_public_holiday_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0008_publicholiday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicholiday",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Public Holiday",
                "verbose_name_plural": "Public Holidays",
            },
        ),
        migrations.RenameField(
            model_name="publicholiday",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="publicholiday",
            name="days",
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(update_public_holiday_seed, rollback_public_holiday_seed),
    ]
