# Generated by Django 5.2.4 on 2026-05-26 12:46

from django.db import migrations, models


def migrate_attendance_statuses(apps, schema_editor):
    Attendance = apps.get_model("hrm", "Attendance")
    # Tối ưu hóa dữ liệu lớn: Cập nhật trực tiếp bằng update(), không load tất cả vào bộ nhớ
    Attendance.objects.filter(status="sick_leave").update(status="paid_leave")
    Attendance.objects.filter(status="other").update(status="unpaid_leave")


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0009_alter_publicholiday_options_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_attendance_statuses, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("working", "Đi làm"),
                    ("paid_leave", "Nghỉ phép có lương"),
                    ("unpaid_leave", "Nghỉ không lương"),
                    ("holiday", "Nghỉ lễ"),
                ],
                max_length=20,
            ),
        ),
    ]
