# Generated by Django 5.2.4 on 2026-05-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0010_alter_attendance_status"),
        ("master_data", "0008_employee_address_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="attendances", to="master_data.employee"
            ),
        ),
        migrations.AlterField(
            model_name="disciplinerecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="disciplines", to="master_data.employee"
            ),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="master_data.employee"
            ),
        ),
        migrations.AlterField(
            model_name="employmentcontract",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="contracts", to="master_data.employee"
            ),
        ),
        migrations.AlterField(
            model_name="employmenthistory",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employment_histories",
                to="master_data.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="leave_requests", to="master_data.employee"
            ),
        ),
        migrations.AlterField(
            model_name="rewardrecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="rewards", to="master_data.employee"
            ),
        ),
    ]
