# Generated by Django 5.2.4 on 2026-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0011_alter_attendance_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
