# Generated by Django 5.2.4 on 2026-06-05 17:08

from django.db import migrations


def link_rewards_and_disciplines(apps, schema_editor):
    RewardRecord = apps.get_model("hrm", "RewardRecord")
    DisciplineRecord = apps.get_model("hrm", "DisciplineRecord")
    SalarySlip = apps.get_model("finance", "SalarySlip")

    # Link historical RewardRecords
    for rw in RewardRecord.objects.filter(salary_slip__isnull=True):
        period_str = rw.reward_date.strftime("%Y-%m")
        slip = SalarySlip.objects.filter(employee=rw.employee, salary_period=period_str).first()
        if slip:
            rw.salary_slip = slip
            rw.save()

    # Link historical DisciplineRecords
    for ds in DisciplineRecord.objects.filter(salary_slip__isnull=True):
        period_str = ds.discipline_date.strftime("%Y-%m")
        slip = SalarySlip.objects.filter(employee=ds.employee, salary_period=period_str).first()
        if slip:
            ds.salary_slip = slip
            ds.save()


def unlink_rewards_and_disciplines(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0012_alter_attendance_date"),
        ("finance", "0014_fixedasset_fixedassetdepreciationlog"),
    ]

    operations = [
        migrations.RunPython(link_rewards_and_disciplines, unlink_rewards_and_disciplines),
    ]
