# Generated by Django 5.2.4 on 2026-06-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0013_link_rewards_disciplines"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"], "verbose_name": "Attendance", "verbose_name_plural": "Attendances"},
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance_employe_c9bb2b_idx",
        ),
    ]
