# Generated by Django 5.2.4 on 2026-06-07 18:58

import django.db.models.deletion
from django.db import migrations, models


def set_existing_hrm_records_to_approved(apps, schema_editor):
    EmploymentHistory = apps.get_model("hrm", "EmploymentHistory")
    RewardRecord = apps.get_model("hrm", "RewardRecord")
    DisciplineRecord = apps.get_model("hrm", "DisciplineRecord")

    EmploymentHistory.objects.filter(status="pending_approval").update(status="approved")
    RewardRecord.objects.filter(status="pending_approval").update(status="approved")
    DisciplineRecord.objects.filter(status="pending_approval").update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_add_finance_pay_invoice_permission"),
        ("finance", "0018_cashflowtransaction_approved_at_and_more"),
        ("hrm", "0014_alter_attendance_options_and_more"),
        ("master_data", "0010_bom_unique_active_bom_per_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinerecord",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disciplinerecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_disciplines",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="disciplinerecord",
            name="status",
            field=models.CharField(
                choices=[("pending_approval", "Pending Approval"), ("approved", "Approved"), ("rejected", "Rejected")],
                db_index=True,
                default="pending_approval",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employmenthistory",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employmenthistory",
            name="status",
            field=models.CharField(
                choices=[("pending_approval", "Pending Approval"), ("approved", "Approved"), ("rejected", "Rejected")],
                db_index=True,
                default="pending_approval",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rewardrecord",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rewardrecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_rewards",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="rewardrecord",
            name="status",
            field=models.CharField(
                choices=[("pending_approval", "Pending Approval"), ("approved", "Approved"), ("rejected", "Rejected")],
                db_index=True,
                default="pending_approval",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="disciplinerecord",
            index=models.Index(fields=["status", "discipline_date"], name="discipline__status_e91226_idx"),
        ),
        migrations.AddIndex(
            model_name="employmenthistory",
            index=models.Index(fields=["status", "effective_date"], name="employment__status_23dfd4_idx"),
        ),
        migrations.AddIndex(
            model_name="rewardrecord",
            index=models.Index(fields=["status", "reward_date"], name="reward_reco_status_46d6bd_idx"),
        ),
        migrations.RunPython(set_existing_hrm_records_to_approved, migrations.RunPython.noop),
    ]
