# Generated by Django 5.2.4 on 2026-06-16 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_add_hrm_payroll_submit"),
        ("hrm", "0015_disciplinerecord_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinerecord",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disciplinerecord",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_disciplines",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="rewardrecord",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rewardrecord",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_rewards",
                to="accounts.user",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending_approval",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rewardrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending_approval",
                max_length=20,
            ),
        ),
    ]
