# Generated by Django 5.2.4 on 2026-06-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0016_disciplinerecord_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardrecord",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("performance_bonus", "Thưởng hiệu quả công việc"),
                    ("initiative", "Thưởng sáng kiến"),
                    ("holiday_bonus", "Thưởng lễ tết"),
                    ("other", "Thưởng khác"),
                ],
                max_length=50,
            ),
        ),
    ]
