# Generated by Django 5.2.4 on 2026-06-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0017_alter_rewardrecord_reward_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employmenthistory",
            name="new_department",
        ),
        migrations.RemoveField(
            model_name="employmenthistory",
            name="new_title",
        ),
        migrations.RemoveField(
            model_name="employmenthistory",
            name="old_department",
        ),
        migrations.RemoveField(
            model_name="employmenthistory",
            name="old_title",
        ),
        migrations.AlterField(
            model_name="employmenthistory",
            name="change_type",
            field=models.CharField(choices=[("salary_change", "Thay đổi lương"), ("other", "Khác")], max_length=50),
        ),
    ]
