# Generated by Django 5.2.4 on 2026-06-16 14:03

from django.db import migrations, models


def backfill_salary_base(apps, schema_editor):
    """
    Copy giá trị Employee.salary_base sang EmploymentContract.salary_base
    cho hợp đồng active đầu tiên của mỗi employee (nếu có).
    """
    Employee = apps.get_model("master_data", "Employee")
    EmploymentContract = apps.get_model("hrm", "EmploymentContract")
    for emp in Employee.objects.exclude(salary_base__isnull=True):
        contract = EmploymentContract.objects.filter(employee=emp, status="active").order_by("start_date").first()
        if contract:
            contract.salary_base = emp.salary_base
            contract.save(update_fields=["salary_base"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0018_remove_employmenthistory_new_department_and_more"),
        ("master_data", "0016_remove_employee_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentcontract",
            name="salary_base",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.RunPython(backfill_salary_base, reverse_noop),
    ]
