# Generated by Django 5.2.4 on 2026-05-20 01:50

from django.db import migrations


def create_supplier_table_if_not_exists(apps, schema_editor):
    table_name = "supplier"
    if table_name not in schema_editor.connection.introspection.table_names():
        Supplier = apps.get_model("procurement", "Supplier")
        schema_editor.create_model(Supplier)


def reverse_supplier_table(apps, schema_editor):
    table_name = "supplier"
    if table_name in schema_editor.connection.introspection.table_names():
        Supplier = apps.get_model("procurement", "Supplier")
        schema_editor.delete_model(Supplier)


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
        ("master_data", "0006_delete_customer_delete_supplier"),
    ]

    operations = [
        migrations.RunPython(create_supplier_table_if_not_exists, reverse_supplier_table),
    ]
