# Generated by Django 5.x on 2026-06-30
from django.db import migrations


def fix_supplier_log_permissions(apps, schema_editor):
    SystemLog = apps.get_model("accounts", "SystemLog")
    # Update allowed_permissions from purchasing.view_log to procurement.supplier_view for supplier logs
    SystemLog.objects.filter(table_name="supplier", allowed_permissions__icontains="purchasing.view_log").update(
        allowed_permissions=["procurement.supplier_view"]
    )


def reverse_fix(apps, schema_editor):
    SystemLog = apps.get_model("accounts", "SystemLog")
    SystemLog.objects.filter(table_name="supplier", allowed_permissions__icontains="procurement.supplier_view").update(
        allowed_permissions=["purchasing.view_log"]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0002_create_supplier_table"),
    ]

    operations = [
        migrations.RunPython(fix_supplier_log_permissions, reverse_fix),
    ]
