# Generated by Django 5.2.4 on 2026-04-22 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentFeeLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("waste_water_volume", models.DecimalField(decimal_places=2, max_digits=15)),
                ("gas_emission_fee_fixed", models.DecimalField(decimal_places=2, max_digits=15)),
                ("variable_fee", models.DecimalField(decimal_places=2, max_digits=15)),
                ("period", models.CharField(max_length=10)),
                ("total_fee", models.DecimalField(decimal_places=2, max_digits=15)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Environment Fee Log",
                "verbose_name_plural": "Environment Fee Logs",
                "db_table": "environment_fee_log",
                "unique_together": {("period",)},
            },
        ),
        migrations.CreateModel(
            name="SalarySlip",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("salary_period", models.CharField(max_length=10)),
                ("union_fee_2pct", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("gross_pay", models.DecimalField(decimal_places=2, max_digits=15)),
                ("deductions", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_method", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_slips",
                        to="master_data.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Slip",
                "verbose_name_plural": "Salary Slips",
                "db_table": "salary_slip",
            },
        ),
        migrations.CreateModel(
            name="TaxReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("report_id", models.CharField(max_length=100, unique=True)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("vat", "VAT"),
                            ("income_tax", "Income Tax"),
                            ("corporate_tax", "Corporate Tax"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("period", models.CharField(max_length=10)),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tax_payable_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tax_paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tax Report",
                "verbose_name_plural": "Tax Reports",
                "db_table": "tax_report",
                "unique_together": {("tax_type", "period")},
            },
        ),
        migrations.CreateModel(
            name="TechnicalCertification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cert_id", models.CharField(max_length=100, unique=True)),
                ("cert_type", models.CharField(max_length=100)),
                ("assessment_fee", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="master_data.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Certification",
                "verbose_name_plural": "Technical Certifications",
                "db_table": "technical_certification",
            },
        ),
    ]
