# Generated by Django 5.2.4 on 2026-05-18 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "payment_type",
                    models.CharField(choices=[("receive", "Receive Money"), ("pay", "Pay Money")], max_length=50),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_date", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payment Entry",
                "verbose_name_plural": "Payment Entries",
                "db_table": "payment_entry",
            },
        ),
    ]
