# Generated by Django 5.2.4 on 2026-05-19 03:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_paymententry_sales_invoice"),
        ("purchasing", "0002_purchaseinvoice_paid_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymententry",
            name="purchase_invoice",
        ),
        migrations.RemoveField(
            model_name="paymententry",
            name="sales_invoice",
        ),
        migrations.CreateModel(
            name="CashFlowTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "payment_type",
                    models.CharField(choices=[("receive", "Receive Money"), ("pay", "Pay Money")], max_length=50),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True, verbose_name="Loại Thu/Chi")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_date", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "purchase_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_flows",
                        to="purchasing.purchaseinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Flow Transaction",
                "verbose_name_plural": "Cash Flow Transactions",
                "db_table": "cash_flow_transaction",
            },
        ),
    ]
