# Generated by Django 5.2.4 on 2026-05-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_remove_paymententry_purchase_invoice_and_more"),
        ("purchasing", "0003_alter_purchaseinvoice_status_purchaseorder_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowtransaction",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_flows",
                to="purchasing.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="cashflowtransaction",
            name="sales_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_flows",
                to="sales.salesinvoice",
            ),
        ),
    ]
