# Generated by Django 5.2.4 on 2026-05-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_cashflowtransaction_purchase_order_and_more"),
        ("sales", "0002_alter_salesinvoice_status_salesorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowtransaction",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_flows",
                to="sales.salesorder",
            ),
        ),
        migrations.DeleteModel(
            name="PaymentEntry",
        ),
    ]
