# Generated by Django 5.2.4 on 2026-05-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_cashflowtransaction_sales_order_delete_paymententry"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryslip",
            name="allowance_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="salaryslip",
            name="base_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="salaryslip",
            name="discipline_deduction_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="salaryslip",
            name="overtime_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="salaryslip",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salaryslip",
            name="reward_amount_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="salaryslip",
            name="gross_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="salaryslip",
            name="net_pay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="salaryslip",
            name="payment_method",
            field=models.CharField(
                blank=True, choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer")], max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="salaryslip",
            name="union_fee_2pct",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
