# Generated by Django 5.2.4 on 2026-05-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_salaryslip_allowance_amount_salaryslip_base_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryslip",
            name="breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
