# Generated by Django 5.2.4 on 2026-05-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_salaryslip_breakdown"),
        ("master_data", "0008_employee_address_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryslip",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="salary_slips", to="master_data.employee"
            ),
        ),
        migrations.AlterField(
            model_name="salaryslip",
            name="salary_period",
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
