# Generated by Django 5.2.4 on 2026-06-03 17:59

from django.db import migrations, models


def migrate_payment_methods(apps, schema_editor):
    CashFlowTransaction = apps.get_model("finance", "CashFlowTransaction")
    for method in ["cash", "bank_transfer", "credit_card", "other"]:
        CashFlowTransaction.objects.filter(category__iexact=method).update(
            payment_method=method, category="Thanh toán hóa đơn"
        )


def reverse_payment_methods(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_alter_salaryslip_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowtransaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="bank_transfer",
                max_length=50,
            ),
        ),
        migrations.RunPython(migrate_payment_methods, reverse_payment_methods),
    ]
