# Generated by Django 5.2.4 on 2026-06-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_technicalcertification_result"),
        ("inventory", "0004_stockentry_shipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalcertification",
            name="stock_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="inventory.stockentry",
                verbose_name="Phiếu nhập kho liên kết",
            ),
        ),
    ]
