# Generated by Django 5.2.4 on 2026-06-05 03:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_technicalcertification_stock_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("asset_code", models.CharField(max_length=100, unique=True)),
                ("asset_name", models.CharField(max_length=255)),
                ("original_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("salvage_value", models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[("straight_line", "Đường thẳng"), ("unit_of_production", "Sản lượng")], max_length=50
                    ),
                ),
                ("useful_life_months", models.IntegerField()),
                ("remaining_life_months", models.IntegerField()),
                ("designed_capacity", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("accumulated_depreciation", models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Fixed Asset",
                "verbose_name_plural": "Fixed Assets",
                "db_table": "fixed_asset",
            },
        ),
        migrations.CreateModel(
            name="FixedAssetDepreciationLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("period", models.CharField(db_index=True, max_length=7)),
                ("depreciation_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_logs",
                        to="finance.fixedasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Asset Depreciation Log",
                "verbose_name_plural": "Fixed Asset Depreciation Logs",
                "db_table": "fixed_asset_depreciation_log",
                "unique_together": {("asset", "period")},
            },
        ),
    ]
