# Generated by Django 5.2.4 on 2026-06-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_fixedasset_fixedassetdepreciationlog"),
        ("master_data", "0009_bom_mold"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="salaryslip",
            constraint=models.UniqueConstraint(
                fields=("employee", "salary_period"), name="unique_salary_slip_per_period"
            ),
        ),
    ]
