# Generated by Django 5.2.4 on 2026-06-05 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_work_order_cancel_and_payroll_approve_permissions"),
        ("finance", "0015_salaryslip_unique_salary_slip_per_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryslip",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salaryslip",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_salary_slips",
                to="accounts.user",
            ),
        ),
        migrations.AlterField(
            model_name="salaryslip",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("calculated", "Calculated"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
