# Generated by Django 5.2.4 on 2026-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_salaryslip_approved_at_salaryslip_approved_by_and_more"),
        ("purchasing", "0008_purchaseorder_expected_delivery_date_and_more"),
        ("sales", "0005_alter_salesinvoice_status_alter_salesorder_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cashflowtransaction",
            index=models.Index(fields=["payment_type", "payment_date"], name="cash_flow_t_payment_8e951f_idx"),
        ),
    ]
