# Generated by Django 5.2.4 on 2026-06-07 18:58

import django.db.models.deletion
from django.db import migrations, models


def set_existing_cash_flows_to_posted(apps, schema_editor):
    CashFlowTransaction = apps.get_model("finance", "CashFlowTransaction")
    # Set status of all existing records to 'posted'
    CashFlowTransaction.objects.filter(status="pending_approval").update(status="posted")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_add_finance_pay_invoice_permission"),
        ("finance", "0017_cashflowtransaction_cash_flow_t_payment_8e951f_idx"),
        ("purchasing", "0008_purchaseorder_expected_delivery_date_and_more"),
        ("sales", "0005_alter_salesinvoice_status_alter_salesorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowtransaction",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflowtransaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_cash_flows",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="cashflowtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("posted", "Posted"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending_approval",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="cashflowtransaction",
            index=models.Index(fields=["status", "payment_date"], name="cash_flow_t_status_aa592c_idx"),
        ),
        migrations.AddIndex(
            model_name="cashflowtransaction",
            index=models.Index(fields=["purchase_order", "status"], name="cash_flow_t_purchas_ed2d95_idx"),
        ),
        migrations.AddIndex(
            model_name="cashflowtransaction",
            index=models.Index(fields=["sales_order", "status"], name="cash_flow_t_sales_o_093848_idx"),
        ),
        migrations.RunPython(set_existing_cash_flows_to_posted, migrations.RunPython.noop),
    ]
