# Generated by Django 5.2.4 on 2026-06-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0018_cashflowtransaction_approved_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TechnicalCertification",
        ),
    ]
