# Generated by Django 5.2.4 on 2026-06-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0019_delete_technicalcertification"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="disposal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="disposal_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="status",
            field=models.CharField(
                choices=[("active", "Đang sử dụng"), ("disposed", "Đã thanh lý")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
