# Generated by Django 5.2.4 on 2026-06-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0020_fixedasset_disposal_date_fixedasset_disposal_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_receive", "Chờ duyệt mua"),
                    ("idle", "Đang nhàn rỗi"),
                    ("active", "Đang sử dụng"),
                    ("pending_dispose", "Chờ duyệt thanh lý"),
                    ("disposed", "Đã thanh lý"),
                ],
                db_index=True,
                default="pending_receive",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="fixedasset",
            index=models.Index(fields=["status", "-updated_at"], name="fa_status_updated_idx"),
        ),
    ]
