# Generated by Django 5.2.4 on 2026-06-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0021_fixedasset_vendor_name_alter_fixedasset_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Tiền mặt"), ("bank_transfer", "Chuyển khoản")],
                default="bank_transfer",
                max_length=50,
                null=True,
            ),
        ),
    ]
