# Generated by Django 5.2.4 on 2026-06-15 07:46

from django.db import migrations, models


def set_uop_time_fields_to_null(apps, schema_editor):
    FixedAsset = apps.get_model("finance", "FixedAsset")
    FixedAsset.objects.filter(depreciation_method="unit_of_production").update(
        useful_life_months=None, remaining_life_months=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0022_fixedasset_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedasset",
            name="remaining_life_months",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="useful_life_months",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(set_uop_time_fields_to_null, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("depreciation_method", "straight_line"), ("useful_life_months__isnull", False)),
                    models.Q(("depreciation_method", "unit_of_production"), ("useful_life_months__isnull", True)),
                    _connector="OR",
                ),
                name="check_fixed_asset_useful_life_by_method",
            ),
        ),
    ]
