# Generated by Django 5.2.4 on 2026-06-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0023_fixedasset_uop_drop_time_attrs"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowtransaction",
            name="fixed_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_flows",
                to="finance.fixedasset",
            ),
        ),
    ]
