# Generated by Django 5.2.4 on 2026-06-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0024_cashflowtransaction_fixed_asset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixedasset",
            name="department",
        ),
    ]
