# Generated by Django 5.2.4 on 2026-06-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0025_remove_fixedasset_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salaryslip",
            name="union_fee_2pct",
        ),
    ]
