# Generated by Django 5.2.4 on 2026-06-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0026_remove_salaryslip_union_fee_2pct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryslip",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("calculated", "Calculated"),
                    ("pending_finance_review", "Pending Finance Review"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
