# Generated by Django 5.2.4 on 2026-06-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0028_migrate_submitted"),
        ("purchasing", "0015_alter_shipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowtransaction",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_flows",
                to="purchasing.shipment",
                verbose_name="Lô hàng",
            ),
        ),
    ]
