# Generated by Django 5.2.4 on 2026-06-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0029_cashflowtransaction_shipment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EnvironmentFeeLog",
        ),
        migrations.DeleteModel(
            name="TaxReport",
        ),
    ]
