# Generated by Django 5.2.4 on 2026-04-22 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_group", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("salary_base", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("is_union_member", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="ModeOfPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("check", "Check"),
                            ("credit_card", "Credit Card"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mode of Payment",
                "verbose_name_plural": "Modes of Payment",
                "db_table": "mode_of_payment",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("supplier_name", models.CharField(max_length=255)),
                ("supplier_group", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "supplier",
            },
        ),
        migrations.CreateModel(
            name="UOM",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Unit of Measurement",
                "verbose_name_plural": "Units of Measurement",
                "db_table": "uom",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_group", models.BooleanField(default=False)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "db_table": "warehouse",
            },
        ),
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_group", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="master_data.itemgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Group",
                "verbose_name_plural": "Item Groups",
                "db_table": "item_group",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("item_code", models.CharField(max_length=100, unique=True)),
                ("item_name", models.CharField(max_length=255)),
                ("hs_code", models.CharField(blank=True, max_length=20, null=True)),
                ("weight_kg", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("recycling_coef_a", models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ("vat_group", models.CharField(blank=True, max_length=50, null=True)),
                ("is_import", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("discontinued", "Discontinued")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "item_group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="master_data.itemgroup"
                    ),
                ),
                (
                    "stock_uom",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="master_data.uom"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "db_table": "item",
            },
        ),
    ]
