# Generated by Django 5.2.4 on 2026-05-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="weight_kg",
        ),
    ]
