# Generated by Django 5.2.4 on 2026-04-22 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOM",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("inactive", "Inactive")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="master_data.item")),
            ],
            options={
                "verbose_name": "Bill of Materials",
                "verbose_name_plural": "Bills of Materials",
                "db_table": "bom",
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("qty", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("released", "Released"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("planned_start_date", models.DateTimeField()),
                ("planned_end_date", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="master_data.item")),
            ],
            options={
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
                "db_table": "work_order",
            },
        ),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("qty", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="master_data.bom"
                    ),
                ),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="master_data.item")),
                (
                    "uom",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="master_data.uom"),
                ),
            ],
            options={
                "verbose_name": "BOM Item",
                "verbose_name_plural": "BOM Items",
                "db_table": "bom_item",
                "unique_together": {("bom", "item")},
            },
        ),
    ]
