# Generated by Django 5.2.4 on 2026-05-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_remove_item_weight_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="production_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wo_production",
                to="master_data.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="source_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wo_source",
                to="master_data.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="target_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wo_target",
                to="master_data.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_approval",
                max_length=20,
            ),
        ),
    ]
