# Generated by Django 5.2.4 on 2026-05-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0003_workorder_production_warehouse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="produced_qty",
            field=models.IntegerField(default=0),
        ),
    ]
