# Generated by Django 5.2.4 on 2026-05-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0004_workorder_produced_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="produced_qty",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
