# Generated by Django 5.2.4 on 2026-05-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0005_alter_workorder_produced_qty_and_more"),
        ("purchasing", "0004_alter_purchaseinvoice_vendor_and_more"),
        ("sales", "0003_alter_salesinvoice_customer_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Customer",
                ),
                migrations.DeleteModel(
                    name="Supplier",
                ),
            ]
        )
    ]
