# Generated by Django 5.2.4 on 2026-05-20 17:17

from django.db import migrations


def seed_metadata(apps, schema_editor):
    # Seed data đã chuyển sang setup-data/setup_local_data.py
    pass


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0006_delete_customer_delete_supplier"),
    ]

    operations = [
        migrations.RunPython(seed_metadata, reverse_seed),
    ]
