# Generated by Django 5.2.4 on 2026-05-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0007_auto_20260521_0017"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="join_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="leave_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="position_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
