# Generated by Django 5.2.4 on 2026-06-05 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_fixedasset_fixedassetdepreciationlog"),
        ("master_data", "0008_employee_address_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="mold",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boms",
                to="finance.fixedasset",
            ),
        ),
    ]
