# Generated by Django 5.2.4 on 2026-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0017_cashflowtransaction_cash_flow_t_payment_8e951f_idx"),
        ("master_data", "0009_bom_mold"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)), fields=("item",), name="unique_active_bom_per_item"
            ),
        ),
    ]
