# Generated by Django 5.2.4 on 2026-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0010_bom_unique_active_bom_per_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("in_progress", "In Progress"),
                    ("pending_production_complete", "Pending Production Complete"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_approval",
                max_length=32,
            ),
        ),
    ]
