# Generated by Django 5.2.4 on 2026-06-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0011_alter_workorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="minimum_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Ngưỡng tối thiểu tồn kho. Nếu NULL sẽ dùng fallback theo UOM.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
