# Generated by Django 5.2.4 on 2026-06-15 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0020_fixedasset_disposal_date_fixedasset_disposal_value_and_more"),
        ("master_data", "0012_item_minimum_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bom",
            name="mold",
        ),
        migrations.CreateModel(
            name="WorkOrderFixedAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "fixed_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order_links",
                        to="finance.fixedasset",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_asset_links",
                        to="master_data.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order - Fixed Asset Link",
                "verbose_name_plural": "Work Order - Fixed Asset Links",
                "db_table": "work_order_fixed_asset",
                "indexes": [
                    models.Index(fields=["work_order"], name="work_order__work_or_a67d5f_idx"),
                    models.Index(fields=["fixed_asset"], name="work_order__fixed_a_3b440a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("work_order", "fixed_asset"), name="unique_work_order_fixed_asset")
                ],
            },
        ),
    ]
