# Generated by Django 5.2.4 on 2026-06-15

from decimal import Decimal
from django.db import migrations, models


def set_default_minimum_threshold(apps, schema_editor):
    Item = apps.get_model("master_data", "Item")
    for item in Item.objects.filter(minimum_threshold__isnull=True).select_related("stock_uom"):
        uom_name = (item.stock_uom.name if item.stock_uom else "").lower()
        if uom_name in ["tấn", "ton", "kg"]:
            default = Decimal("0.5")
        elif uom_name in ["cái", "piece", "pcs"]:
            default = Decimal("200.0")
        else:
            default = Decimal("10.0")
        Item.objects.filter(pk=item.pk).update(minimum_threshold=default)


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0013_remove_bom_mold_workorderfixedasset"),
    ]

    operations = [
        migrations.RunPython(set_default_minimum_threshold, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="item",
            name="minimum_threshold",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.0"),
                help_text="Ngưỡng tối thiểu tồn kho. Bắt buộc nhập.",
                max_digits=18,
            ),
        ),
    ]
