# Generated by Django 5.2.4 on 2026-06-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0014_item_minimum_threshold_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="is_union_member",
        ),
    ]
