# Generated by Django 5.2.4 on 2026-06-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0015_remove_employee_is_union_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position_title",
        ),
    ]
