# Generated by Django 5.2.4 on 2026-06-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0016_remove_employee_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="salary_base",
        ),
    ]
