# Generated by Django 5.2.4 on 2026-04-22 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("issue", "Issue"),
                            ("transfer", "Transfer"),
                            ("manufacture", "Manufacture"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("posting_date", models.DateTimeField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted"), ("posted", "Posted")],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Entry",
                "verbose_name_plural": "Stock Entries",
                "db_table": "stock_entry",
            },
        ),
        migrations.CreateModel(
            name="StockEntryDetail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="master_data.item")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="details", to="inventory.stockentry"
                    ),
                ),
                (
                    "source_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_entries_from",
                        to="master_data.warehouse",
                    ),
                ),
                (
                    "target_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_entries_to",
                        to="master_data.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Entry Detail",
                "verbose_name_plural": "Stock Entry Details",
                "db_table": "stock_entry_detail",
            },
        ),
        migrations.CreateModel(
            name="StockLedger",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("posting_date", models.DateTimeField()),
                ("actual_quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                ("voucher_number", models.CharField(blank=True, max_length=100, null=True)),
                ("voucher_type", models.CharField(blank=True, max_length=50, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="master_data.item")),
                (
                    "warehouse",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="master_data.warehouse"),
                ),
            ],
            options={
                "verbose_name": "Stock Ledger",
                "verbose_name_plural": "Stock Ledgers",
                "db_table": "stock_ledger",
                "indexes": [
                    models.Index(fields=["item", "warehouse", "posting_date"], name="stock_ledge_item_id_89a0fb_idx")
                ],
            },
        ),
    ]
