# Generated by Django 5.2.4 on 2026-05-20 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("purchasing", "0004_alter_purchaseinvoice_vendor_and_more"),
        ("sales", "0003_alter_salesinvoice_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentry",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_entries",
                to="purchasing.purchaseorder",
                verbose_name="Đơn mua hàng",
            ),
        ),
        migrations.AddField(
            model_name="stockentry",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_entries",
                to="sales.salesorder",
                verbose_name="Đơn bán hàng",
            ),
        ),
    ]
