# Generated by Django 5.2.4 on 2026-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockentry_purchase_order_stockentry_sales_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("posted", "Posted"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
