# Generated by Django 5.2.4 on 2026-06-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_stockentry_status"),
        ("purchasing", "0006_shipment_purchaseinvoice_block_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentry",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_entries",
                to="purchasing.shipment",
                verbose_name="Lô hàng",
            ),
        ),
    ]
