# Generated by Django 5.2.4 on 2026-06-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_stockentry_shipment"),
        ("master_data", "0009_bom_mold"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentry",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_entries",
                to="master_data.workorder",
                verbose_name="Lệnh sản xuất",
            ),
        ),
    ]
