# Generated by Django 5.2.4 on 2026-06-05 17:08

from django.db import migrations


def populate_work_order(apps, schema_editor):
    StockEntry = apps.get_model("inventory", "StockEntry")
    WorkOrder = apps.get_model("master_data", "WorkOrder")

    for wo in WorkOrder.objects.all():
        StockEntry.objects.filter(work_order__isnull=True, remarks__contains=wo.name).update(work_order=wo)


def rollback_work_order(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_add_work_order_fk"),
        ("master_data", "0009_bom_mold"),
    ]

    operations = [
        migrations.RunPython(populate_work_order, rollback_work_order),
    ]
