# Generated by Django 5.2.4 on 2026-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_populate_work_order_from_remarks"),
        ("master_data", "0010_bom_unique_active_bom_per_item"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stockentrydetail",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="stock_detail_qty_positive"
            ),
        ),
    ]
