# Generated by Django 5.2.4 on 2026-06-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_stockentrydetail_stock_detail_qty_positive"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentry",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt"),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="posting_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
