# Generated by Django 5.2.4 on 2026-04-22 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOM",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="boms", to="master_data.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill of Materials",
                "verbose_name_plural": "Bills of Materials",
                "db_table": "bom",
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("quantity", models.IntegerField()),
                ("planned_start_date", models.DateField()),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "bom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders",
                        to="manufacturing.bom",
                    ),
                ),
                (
                    "production_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="master_data.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
                "db_table": "work_order",
            },
        ),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bom_items", to="master_data.item"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="manufacturing.bom"
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Item",
                "verbose_name_plural": "BOM Items",
                "db_table": "bom_item",
                "unique_together": {("parent", "item")},
            },
        ),
    ]
