# Generated by Django 5.2.4 on 2026-05-20 01:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Customer",
                    fields=[
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("is_active", models.BooleanField(default=True)),
                        ("name", models.CharField(max_length=255, unique=True)),
                        ("customer_name", models.CharField(max_length=255)),
                        ("customer_group", models.CharField(blank=True, max_length=255, null=True)),
                        ("contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                        ("contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                        ("address", models.TextField(blank=True, null=True)),
                    ],
                    options={
                        "verbose_name": "Customer",
                        "verbose_name_plural": "Customers",
                        "db_table": "customer",
                    },
                ),
            ]
        )
    ]
