# Generated by Django 5.2.4 on 2026-05-20 01:50

from django.db import migrations


def create_customer_table_if_not_exists(apps, schema_editor):
    table_name = "customer"
    if table_name not in schema_editor.connection.introspection.table_names():
        Customer = apps.get_model("crm", "Customer")
        schema_editor.create_model(Customer)


def reverse_customer_table(apps, schema_editor):
    table_name = "customer"
    if table_name in schema_editor.connection.introspection.table_names():
        Customer = apps.get_model("crm", "Customer")
        schema_editor.delete_model(Customer)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        ("master_data", "0006_delete_customer_delete_supplier"),
    ]

    operations = [
        migrations.RunPython(create_customer_table_if_not_exists, reverse_customer_table),
    ]
