# Generated by Django 5.2.4 on 2026-06-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_create_customer_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Hạn mức nợ"),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_credit_locked",
            field=models.BooleanField(default=False, verbose_name="Khóa tín dụng chủ động"),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms",
            field=models.CharField(default="NET30", max_length=50, verbose_name="Điều khoản thanh toán"),
        ),
    ]
