# Static configuration registry for all 27 widgets

WIDGETS_REGISTRY = {
    "sales_today_revenue": {
        "permission": "sales.view_order",
        "type": "metric",
        "size": "1x1",
        "title": "Doanh thu hôm nay",
        "quick_links": ["/sales/orders"],
    },
    "sales_draft_orders": {
        "permission": "sales.view_order",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn hàng nháp",
        "quick_links": ["/sales/orders?status=draft"],
    },
    "sales_pending_credit_bypass": {
        "permission": "sales.approve_credit_bypass",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn bán hàng chờ duyệt vượt hạn mức",
        "quick_links": ["/sales/orders?status=pending_credit_approval"],
    },
    "sales_pending_fulfillment": {
        "permission": "sales.view_order",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn bán hàng chờ giao hàng",
        "quick_links": ["/sales/orders?status=pending"],
    },
    "purchasing_active_po_count": {
        "permission": "purchasing.view_order",
        "type": "metric",
        "size": "1x1",
        "title": "Đơn mua hàng đang hoạt động",
        "quick_links": ["/purchasing/orders?status=pending"],
    },
    "purchasing_draft_orders": {
        "permission": "purchasing.view_order",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn mua hàng nháp",
        "quick_links": ["/purchasing/orders?status=draft"],
    },
    "purchasing_pending_delivery": {
        "permission": "purchasing.view_order",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn mua hàng chờ nhận hàng",
        "quick_links": ["/purchasing/orders?status=pending"],
    },
    "purchasing_pending_qc": {
        "permission": "purchasing.manage_qc",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lô hàng chờ kiểm QC",
        "quick_links": ["/purchasing/certifications"],
    },
    "purchasing_pending_logistic_fees": {
        "permission": "purchasing.allocate_landed_cost",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lô hàng chờ phân bổ chi phí",
        "quick_links": ["/purchasing/shipments"],
    },
    "purchasing_blocked_invoices": {
        "permission": "purchasing.view_invoice",
        "type": "list_summary",
        "size": "1x2",
        "title": "Hóa đơn mua bị chặn",
        "quick_links": ["/purchasing/invoices?status=blocked"],
    },
    "inventory_pending_entry_count": {
        "permission": "inventory.view",
        "type": "metric",
        "size": "1x1",
        "title": "Giao dịch kho chờ nhập",
        "quick_links": ["/inventory/stock-balances"],
    },
    "inventory_low_stock": {
        "permission": "inventory.view",
        "type": "list_summary",
        "size": "1x2",
        "title": "Cảnh báo tồn kho thấp",
        "quick_links": ["/inventory/stock-balances"],
    },
    "inventory_pending_entries": {
        "permission": "inventory.view",
        "type": "list_summary",
        "size": "2x2",
        "title": "Yêu cầu chuyển kho chờ thực hiện",
        "quick_links": ["/inventory/transfers"],
    },
    "finance_cashflow_chart": {
        "permission": "finance.view_cash_flow",
        "type": "mini_chart",
        "size": "2x2",
        "title": "Biểu đồ dòng tiền tuần",
        "quick_links": ["/finance/cashflow"],
    },
    "finance_cashflow_summary": {
        "permission": "finance.view_cash_flow",
        "type": "metric",
        "size": "1x1",
        "title": "Tóm tắt dòng tiền tháng",
        "quick_links": ["/finance/cashflow"],
    },
    "finance_unpaid_purchase_invoices": {
        "permission": "purchasing.view_invoice",
        "type": "list_summary",
        "size": "1x2",
        "title": "Hóa đơn mua chưa thanh toán",
        "quick_links": ["/purchasing/invoices?status=unpaid"],
    },
    "finance_unpaid_sales_invoices": {
        "permission": "sales.view_invoice",
        "type": "list_summary",
        "size": "1x2",
        "title": "Hóa đơn bán chưa thanh toán",
        "quick_links": ["/sales/invoices?status=unpaid"],
    },
    "finance_depreciation_status": {
        "permission": "finance.run_depreciation",
        "type": "metric",
        "size": "1x1",
        "title": "Khấu hao tài sản tháng",
        "quick_links": ["/finance/fixed-assets"],
    },
    "hrm_payroll_lifecycle_status": {
        "permission": "finance.view_salaryslip",
        "type": "metric",
        "size": "1x1",
        "title": "Trạng thái bảng lương tháng",
        "quick_links": ["/hrm/salary-slips"],
    },
    "hrm_pending_leave_requests": {
        "permission": "hrm.change_leaverequest",
        "type": "list_summary",
        "size": "1x2",
        "title": "Yêu cầu nghỉ phép chờ duyệt",
        "quick_links": ["/hrm/leave-requests"],
    },
    "hrm_expiring_contracts": {
        "permission": "hrm.view_employee",
        "type": "list_summary",
        "size": "1x2",
        "title": "Hợp đồng lao động sắp hết hạn",
        "quick_links": ["/hrm/contracts"],
    },
    "hrm_employees_without_contract": {
        "permission": "hrm.add_employmentcontract",
        "type": "list_summary",
        "size": "1x2",
        "title": "Nhân viên chưa ký HĐ",
        "quick_links": ["/hrm/contracts"],
    },
    "hrm_today_attendance_rate": {
        "permission": "hrm.view_attendance",
        "type": "metric",
        "size": "1x1",
        "title": "Tỷ lệ đi làm hôm nay",
        "quick_links": ["/hrm/attendance"],
    },
    "manufacturing_pending_wo_approval": {
        "permission": "manufacturing.work_order_approve",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lệnh sản xuất chờ duyệt",
        "quick_links": ["/manufacturing/work-orders"],
    },
    "manufacturing_active_wos": {
        "permission": "manufacturing.work_order_view",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lệnh sản xuất đang thực hiện",
        "quick_links": ["/manufacturing/work-orders"],
    },
    "manufacturing_pending_declarations": {
        "permission": "manufacturing.work_order_declare",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lệnh sản xuất chờ khai báo",
        "quick_links": ["/manufacturing/work-orders"],
    },
    "manufacturing_pending_completion": {
        "permission": "manufacturing.work_order_complete",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lệnh sản xuất chờ nghiệm thu",
        "quick_links": ["/manufacturing/work-orders"],
    },
}
