# Static configuration registry for all 27 widgets

WIDGETS_REGISTRY = {
    "sales_today_revenue": {
        "permission": "sales.view_order",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn bán hàng hôm nay",
        "quick_links": ["/sales?tab=orders"],
    },
    "sales_draft_orders": {
        "permission": "sales.view_order",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn hàng nháp",
        "quick_links": ["/sales?tab=orders&status=draft"],
    },
    "sales_pending_credit_bypass": {
        "permission": "sales.approve_credit_bypass",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn bán hàng chờ duyệt vượt hạn mức",
        "quick_links": ["/sales?tab=orders&status=pending_credit_approval"],
    },
    "sales_pending_fulfillment": {
        "permission": "inventory.stock_issue",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn bán hàng chờ giao hàng",
        "quick_links": ["/inventory?tab=entries&status=draft"],
    },
    "purchasing_active_po_count": {
        "permission": "purchasing.view_order",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn mua hàng hoạt động",
        "quick_links": ["/purchasing?tab=orders&status=pending"],
    },
    "purchasing_draft_orders": {
        "permission": "purchasing.view_order",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn mua hàng nháp",
        "quick_links": ["/purchasing?tab=orders&status=draft"],
    },
    "purchasing_pending_delivery": {
        "permission": "inventory.stock_in",
        "type": "list_summary",
        "size": "1x2",
        "title": "Đơn mua hàng chờ nhận hàng",
        "quick_links": ["/inventory?tab=entries&status=draft"],
    },
    "purchasing_pending_qc": {
        "permission": "purchasing.manage_qc",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lô hàng chờ kiểm QC",
        "quick_links": ["/purchasing?tab=shipment"],
    },
    "purchasing_pending_logistic_fees": {
        "permission": "purchasing.allocate_landed_cost",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lô hàng chờ phân bổ chi phí",
        "quick_links": ["/purchasing?tab=shipment"],
    },
    "purchasing_blocked_invoices": {
        "permission": "purchasing.verify_matching",
        "type": "list_summary",
        "size": "1x2",
        "title": "Hóa đơn mua bị chặn",
        "quick_links": ["/purchasing?tab=invoices&status=blocked"],
    },
    "inventory_pending_entry_count": {
        "permission": "inventory.stock_in_approve",
        "type": "list_summary",
        "size": "1x2",
        "title": "Phiếu nhập kho chờ duyệt",
        "quick_links": ["/inventory?tab=entries&status=draft"],
    },
    "inventory_low_stock": {
        "permission": "inventory.view",
        "type": "list_summary",
        "size": "1x2",
        "title": "Cảnh báo tồn kho thấp",
        "quick_links": ["/inventory?tab=ledger"],
    },
    "inventory_pending_entries": {
        "permission": "inventory.stock_transfer",
        "type": "list_summary",
        "size": "2x2",
        "title": "Yêu cầu chuyển kho chờ thực hiện",
        "quick_links": ["/inventory?tab=entries&status=draft"],
    },
    "finance_cashflow_chart": {
        "permission": "finance.view_cash_flow",
        "type": "mini_chart",
        "size": "2x2",
        "title": "Biểu đồ dòng tiền tuần",
        "quick_links": ["/finance"],
    },
    "finance_cashflow_summary": {
        "permission": "finance.view_cash_flow",
        "type": "list_summary",
        "size": "1x2",
        "title": "Giao dịch dòng tiền tháng",
        "quick_links": ["/finance"],
    },
    "finance_unpaid_purchase_invoices": {
        "permission": "finance.pay_invoice",
        "type": "list_summary",
        "size": "1x2",
        "title": "Hóa đơn mua chưa thanh toán",
        "quick_links": ["/finance?tab=ap&status=unpaid"],
    },
    "finance_unpaid_sales_invoices": {
        "permission": "sales.view_invoice",
        "type": "list_summary",
        "size": "1x2",
        "title": "Hóa đơn bán chưa thanh toán",
        "quick_links": ["/sales?tab=invoices&status=unpaid"],
    },
    "finance_depreciation_status": {
        "permission": "finance.view_fixed_asset",
        "type": "list_summary",
        "size": "1x2",
        "title": "Khấu hao tài sản cố định",
        "quick_links": ["/finance/fixed-assets"],
    },
    "hrm_payroll_lifecycle_status": {
        "permission": "finance.view_salaryslip",
        "type": "list_summary",
        "size": "1x2",
        "title": "Bảng lương chờ duyệt & thanh toán",
        "quick_links": ["/hrm?tab=salary"],
    },
    "hrm_pending_leave_requests": {
        "permission": "hrm.change_leaverequest",
        "type": "list_summary",
        "size": "1x2",
        "title": "Yêu cầu nghỉ phép chờ duyệt",
        "quick_links": ["/hrm?tab=leave"],
    },
    "hrm_expiring_contracts": {
        "permission": "hrm.change_employmentcontract",
        "type": "list_summary",
        "size": "1x2",
        "title": "Hợp đồng lao động sắp hết hạn",
        "quick_links": ["/hrm?tab=employees"],
    },
    "hrm_today_attendance_rate": {
        "permission": "hrm.view_attendance",
        "type": "list_summary",
        "size": "1x2",
        "title": "Nhân viên vắng mặt hôm nay",
        "quick_links": ["/hrm?tab=attendance"],
    },
    "manufacturing_pending_wo_approval": {
        "permission": "manufacturing.work_order_approve",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lệnh sản xuất chờ duyệt",
        "quick_links": ["/bom?tab=wo&status=pending_approval"],
    },
    "manufacturing_active_wos": {
        "permission": "manufacturing.work_order_view",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lệnh sản xuất đang thực hiện",
        "quick_links": ["/bom?tab=wo&status=in_progress"],
    },
    "manufacturing_pending_declarations": {
        "permission": "manufacturing.work_order_view",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lệnh sản xuất sắp trễ hạn",
        "quick_links": ["/bom?tab=wo&status=in_progress"],
    },
    "manufacturing_pending_completion": {
        "permission": "manufacturing.work_order_complete",
        "type": "list_summary",
        "size": "1x2",
        "title": "Lệnh sản xuất chờ nghiệm thu",
        "quick_links": ["/bom?tab=wo&status=in_progress"],
    },
}
