# Static configuration registry for all 27 widgets

WIDGETS_REGISTRY = {
    "sales_today_revenue": {
        "permission": "sales.view_order",
        "type": "line_chart",
        "size": "2x2",
        "title": "Doanh thu hôm nay",
        "quick_links": ["/sales?tab=orders"],
    },
    "sales_draft_orders": {
        "permission": "sales.view_order",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Đơn bán hàng nháp",
        "quick_links": ["/sales?tab=orders&status=draft"],
    },
    "sales_pending_credit_bypass": {
        "permission": "sales.approve_credit_bypass",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Đơn bán hàng chờ duyệt vượt hạn mức",
        "quick_links": ["/sales?tab=orders&status=pending_credit_approval"],
    },
    "sales_pending_fulfillment": {
        "permission": "sales.view_order",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Đơn bán hàng đang hoạt động",
        "quick_links": ["/sales?tab=orders&status=pending"],
    },
    "purchasing_active_po_count": {
        "permission": "purchasing.view_order",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Đơn mua hàng hoạt động",
        "quick_links": ["/purchasing?tab=orders&status=pending"],
    },
    "purchasing_draft_orders": {
        "permission": "purchasing.view_order",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Đơn mua hàng nháp",
        "quick_links": ["/purchasing?tab=orders&status=draft"],
    },
    "purchasing_pending_logistic_fees": {
        "permission": "purchasing.view_shipment",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Lô Hàng Chờ Duyệt",
        "quick_links": ["/purchasing?tab=shipment&status=draft"],
    },
    "inventory_low_stock": {
        "permission": "inventory.view",
        "type": "donut_chart",
        "size": "2x2",
        "title": "Theo dõi linh kiện",
        "quick_links": ["/inventory?tab=ledger"],
    },
    "inventory_pending_entries": {
        "permission": "inventory.stock_transfer",
        "type": "kpi_list",
        "size": "2x2",
        "title": "Yêu cầu chuyển kho chờ thực hiện",
        "quick_links": ["/inventory?tab=entries&status=draft"],
    },
    "finance_cashflow_overview": {
        "permission": "finance.view_cash_flow",
        "type": "cashflow_overview",
        "size": "2x2",
        "title": "Tổng quan & Xu hướng dòng tiền",
        "quick_links": ["/finance"],
    },
    "finance_unpaid_purchase_invoices": {
        "permission": "finance.pay_invoice",
        "type": "donut_chart",
        "size": "1x2",
        "title": "Hóa đơn mua chưa thanh toán",
        "quick_links": ["/finance?tab=purchase_invoices&status=unpaid,partial"],
    },
    "finance_unpaid_sales_invoices": {
        "permission": "finance.collect_invoice",
        "type": "donut_chart",
        "size": "1x2",
        "title": "Hóa đơn bán chưa thanh toán",
        "quick_links": ["/finance?tab=sales_invoices&status=unpaid,partial"],
    },
    "finance_depreciation_status": {
        "permission": "finance.view_fixed_asset",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Khấu hao tài sản cố định",
        "quick_links": ["/finance/fixed-assets"],
    },
    "hrm_payroll_lifecycle_status": {
        "permission": "finance.view_salaryslip",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Bảng lương chờ duyệt & thanh toán",
        "quick_links": ["/hrm?tab=salary"],
    },
    "hrm_pending_leave_requests": {
        "permission": "hrm.change_leaverequest",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Yêu cầu nghỉ phép chờ duyệt",
        "quick_links": ["/hrm?tab=leave"],
    },
    "hrm_expiring_contracts": {
        "permission": "hrm.change_employmentcontract",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Hợp đồng lao động sắp hết hạn",
        "quick_links": ["/hrm?tab=employees"],
    },
    "hrm_today_attendance_rate": {
        "permission": "hrm.view_attendance",
        "type": "gauge",
        "size": "1x2",
        "title": "Theo dõi vắng mặt",
        "quick_links": ["/hrm?tab=attendance"],
    },
    "manufacturing_pending_wo_approval": {
        "permission": "manufacturing.work_order_approve",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Lệnh sản xuất chờ duyệt",
        "quick_links": ["/bom?tab=wo&status=pending_approval"],
    },
    "manufacturing_active_wos": {
        "permission": "manufacturing.work_order_view",
        "type": "stacked_progress",
        "size": "2x2",
        "title": "Lệnh sản xuất đang thực hiện",
        "quick_links": ["/bom?tab=wo&status=in_progress"],
    },
    "manufacturing_pending_declarations": {
        "permission": "manufacturing.work_order_view",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Lệnh sản xuất sắp trễ hạn",
        "quick_links": ["/bom?tab=wo&status=in_progress"],
    },
    "manufacturing_pending_completion": {
        "permission": "manufacturing.work_order_complete",
        "type": "kpi_list",
        "size": "1x2",
        "title": "Lệnh sản xuất chờ nghiệm thu",
        "quick_links": ["/bom?tab=wo&status=in_progress"],
    },
}
